---
title: "Analyse"
author: "Fabian Comanns, Peter Gödde, Nicole Herbolt, Insa Menzel"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
install.packages("datapasta")

library(devtools)
#devtools::install_github("HCIC/r-tools")
library(tidyverse)
library(qualtRics)
library(jmv)
library(likert)
library(psych)
library(sjlabelled)
library(datapasta) 
```

# Daten laden und bereinigen

```{r}
filename <- "data/clickbaitdata.csv"
raw <- readSurvey (filename)

raw %>%
  filter(Status == "IP Address") %>% 
  filter(Progress == 100) -> raw

raw.short <- raw[,c(-1:-17, -21, -139:-140)]

raw.head <- raw.short[,c(-1:-22, -119:-120)]

#write.csv2(raw.head, "data/raw.head.csv")
```

```{r, Kategoriale und numerische Variablen}
raw.short$Gender <- as.factor(raw.short$Gender)
raw.short$Ausbildung <- as.factor(raw.short$Ausbildung)
raw.short$Age <- as.numeric(raw.short$Age)

#Schlagzeilen als kategoriale Variablen:

raw.short$Schlagzeile1 <- as.factor(raw.short$Schlagzeile1)
raw.short$Schlagzeile2 <- as.factor(raw.short$Schlagzeile2)
raw.short$Schlagzeile3 <- as.factor(raw.short$Schlagzeile3)
raw.short$Schlagzeile4 <- as.factor(raw.short$Schlagzeile4)
raw.short$Schlagzeile5 <- as.factor(raw.short$Schlagzeile5)
raw.short$Schlagzeile6 <- as.factor(raw.short$Schlagzeile6)
raw.short$Schlagzeile7 <- as.factor(raw.short$Schlagzeile7)
raw.short$Schlagzeile8 <- as.factor(raw.short$Schlagzeile8)
raw.short$Schlagzeile9 <- as.factor(raw.short$Schlagzeile9)
raw.short$Schlagzeile10 <- as.factor(raw.short$Schlagzeile10)
raw.short$Schlagzeile11 <- as.factor(raw.short$Schlagzeile11)
raw.short$Schlagzeile12 <- as.factor(raw.short$Schlagzeile12)


```

```{r, Mapping}
#Schlagzeile1
mapping <- c("Die EU-Kommission möchte das Ziel der Klimaneutralität bis 2050 gesetzlich festschreiben. Für Gebiete, die besonders von dem damit einhergehenden Strukturwandel betroffen wären, soll ein Übergangsfonds in zweistelliger Milliardenhöhe geschaffen werden."= 1, "Um das Ziel der Klimaneutralität bis 2050 erreichen zu können, hat die EU-Komissionen einen Übergangsfonds für Gebiete gefordert, die von dem Strukturwandel betroffen wären. Die Forderung wurde abgelehnt."= 0, "Die EU-Kommission hat beschlossen: Um die Klimaneutralität bis 2050 zu erreichen, werden alle Gebiete ab Januar 2020 mit einem Zuschuss von 1 Million Euro unterstützt. Das ist seit kurzem rechtlich geregelt."= 0)

raw.short$head_1 <- mapping[as.character(raw.short$Schlagzeile1)]

#Schlagzeile2
mapping <- c("Bill Gates forscht mit seinem Konzern Microsoft an einer effizienteren Methode der Energie Speicherung."= 0, "Bill Gates hat ein amerikanisches Unternehmen aufgekauft, das an neuartigen Brennstoffzellen forscht."= 0, "Bill Gates erwartet in den nächsten 15 Jahren eine technische Alternative zu herkömmlichen Antriebstechnologien." = 1)
  
raw.short$head_2 <- mapping[as.character(raw.short$Schlagzeile2)]

#Schlagzeile3

mapping <- c("Nach drei Tagen in Polizeigewahrsam verstirbt ein 37-Jähriger auf der Wache. Dieser hatte zuvor in betrunkenem Zustand einen Polizeibeamten mit einem Messer angegriffen. Die zwei involvierten Polizeibeamten konnten die Gewalttat verhindern und den Angreifer in Gewahrsam nehmen."= 0, "Nach einem Familiendrama in Schleswig-Holstein wurde ein 25-Jähriger festgenommen, weil er seiner Mutter gegenüber gewalttätig geworden sein soll. Nach drei Tagen in Polizeigewahrsam verstarb der junge Mann, der unter einer Herzschwäche litt."= 0, "Ein betrunkener Ladendieb (37) wurde nach auffälligem Verhalten von Polizeibeamten mit auf das Revier genommen. Kaum dort angekommen verschlechterte sich der gesundheitliche Zustand des Festgenommenen. Er musste ins Krankenhaus gebracht werden und verstarb dort drei Tage später."= 1)

raw.short$head_3 <- mapping[as.character(raw.short$Schlagzeile3)]

  
#Schlagzeile4

mapping <- c("Der Rechtsausschuss des Bundestags hat dem Vorsitzenden Stephan Brandner eine letzte Abmahnung erteilt. Sollte der AfD-Abgeordnete sich noch einen weiteren Fehltritt erlauben durch unangebrachte Twitter-Posts oder radikale Kommentare, wird er als Vorsitzender abgewählt."= 0, "Der Rechtsausschuss des Bundestages hat den AfD-Abgeordneten Stephan Brandner als Vorsitzenden abgewählt. Dabei handelt es sich um einen einmaligen Vorfall in der 70-jährigen Geschichte des Parlaments." = 1, "Der AfD-Politiker Stephan Brandner soll als Rechtsausschuss-Vorsitzender abgewählt werden. Da dies in der 70-jährigen Geschichte des Parlaments noch nie geschehen ist, wird nun geprüft, ob das Abwählen des Vorsitzenden möglich ist." =0 )

raw.short$head_4 <- mapping[as.character(raw.short$Schlagzeile4)]

  
#Schlagzeile5

mapping <- c("Daniela Katzenberger verkündet ihre Schwangerschaft."= 0, "Daniela Katzenberger präsentiert sich mit einer Baby-Puppe."= 1, "Daniela Katzenberger stellt ihre eigene Baby-Mode-Kollektion vor."= 0)

raw.short$head_5 <- mapping[as.character(raw.short$Schlagzeile5)]

  
#Schlagzeile6

mapping <- c("Gerüchten zufolge haben sich die TV-Moderatorin Anne Will und die Kommunikationswissenschaftlerin Miriam Meckel getrennt. Das Paar hat bekannt gegeben, dass es sich dabei um falsche Informationen handelt. Sie sind weiterhin glücklich verheiratet."= 0, "Gerüchten zufolge haben sich die TV-Moderatorin Anne Will und die Kommunikationswissenschaftlerin Miriam Meckel getrennt. Dieses Gerücht ist schon häufiger in den Nachrichten gewesen, wurde jedoch immer widerlegt. Das Paar schweigt zu diesen Vermutungen."= 0, "TV-Moderatorin Anne Will und Kommunikationswissenschaftlerin Miriam Meckel haben ihre Trennung verkündet. Die beiden galten als prominentes lesbisches Paar." =1)

raw.short$head_6 <- mapping[as.character(raw.short$Schlagzeile6)]

  
#Schlagzeile7

mapping <- c("Bundestag stimmt über ein größeres Budget für Dienstwagen von Regierungspolitikern."= 0, "Kein Dienstwagen der Regierungspolitiker in Bund und Ländern hält die EU-Grenzwerte ein."= 1, "Regierungspolitiker nutzen Ihre Dienstwagen hauptsächlich für private Zwecke."= 0)

raw.short$head_7 <- mapping[as.character(raw.short$Schlagzeile7)]

#Schlagzeile8

mapping <- c("Die Bundesregierung testet Standorte, um bemannte Raketen ins Weltall schicken zu können."= 0, "Die Bundesregierung testet Standorte, von denen kleine Trägerraketen kleine Satelliten ins All schicken können."= 1, "In Deutschland soll ein vergleichbarer Weltraumbahnhof wie „Cape Canaveral“ in Florida gebaut werden."= 0)

raw.short$head_8 <- mapping[as.character(raw.short$Schlagzeile8)]

#Schlagzeile9

mapping <- c("Der YouTuber Rezo hat mit seinem Video \"Die Zerstörung der CDU\" dazu beigetragen, die deutschen Jugendlichen mehr für Politik zu interessieren. Die deutschen Jugendlichen selbst bezeichnen es als ein sehr erfolgreiches Video." = 0, "Laut einer Umfrage der Plattform YouTube erinnern sich 90% der Jugendlichen zwischen 12 und 20 Jahren am besten an das Video \"Die Zerstörung der CDU\" von dem deutschen YouTuber Rezo. Die Anzahl der Aufrufe besagt allerdings, dass sich Rezo mit seinem Video nur auf Platz 5 der erfolgreichsten Videos in Deutschland befindet."= 0, "Der YouTuber Rezo führt mit seinem Video \"Die Zerstörung der CDU\" das Ranking der erfolgreichsten Videos des Jahres in Deutschland an. Mit mehr als 16 Millionen Aufrufen ist er auf Platz 1."= 1)

raw.short$head_9 <- mapping[as.character(raw.short$Schlagzeile9)]


#Schlagzeile10

mapping <- c("Überraschung bei der TV-Show “Adventsfest”: Florian Silbereisen stellt seine neue Lebensgefährtin Diana vor - und bittet sie vor laufenden Kameras, seine Frau zu werden."= 0, "Während einer von Florian Silbereisen moderierten Sendung bittet der Trompeter Stefan Mross seine Freundin Anna-Carina Woitschak, seine Frau zu werden."= 1, "Florian Silbereisen legt eine Show-Einlage ein: Im Zuge seiner Moderation des “Adventsfests” geht er auf Knie und bittet eine Promi-Dame um ihre Hand - und zwar Uschi Glas! Im Nachhinein wurde aufgelöst, dass der Antrag nur Teil der Show war."=0)

raw.short$head_10 <- mapping[as.character(raw.short$Schlagzeile10)]

#Schlagzeile11

mapping <- c("Aufgrund von Datenschutzbestimmungen, werden die Social-Media Plattformen im Jahr 2020 vom deutschen Markt genommen."= 0, "Ein Landesgericht in Deutschland erkennt Patentverstöße von Facebook und Whatsapp gegenüber BlackBerry an."= 1, "Die nicht erfüllten Auflagen, zur Kontrolle von Hasskommentaren im Netz, führen zu einer vorübergehenden Sperrung von Facebook, wenn diese nicht innerhalb der nächste 4 Monate erfüllt werden."= 0 )

raw.short$head_11 <- mapping[as.character(raw.short$Schlagzeile11)]

#Schlagzeile12

mapping <- c("Das Paar Heidi Klum und Tom Kaulitz hat sich auf der berühmten Halloween-Party von Heidi Klum zerstritten. Sie haben die Party getrennt verlassen und Tom hat die nächsten zwei Nächte bei seinem Bruder Bill verbracht."= 0, "Heidi Klum und Tom Kaulitz haben sich nach der berühmten Halloween-Party von Heidi Klum über zahlreiche Patzer des Caterers beschwert und 10% der Ausgaben für Essen und Getränke zurückerhalten."= 0, "Die berühmte Halloween-Party von Heidi Klum war ein Flop. Angekündigte Stars wie Gigi Hadid, Nicole Scherzinger oder Jennifer Lopez sind nicht erschienen."= 1)

raw.short$head_12 <- mapping[as.character(raw.short$Schlagzeile12)]

```


#Skalenbenennung
```{r, Skalenbenennung}
skala.zutreffen <- c("Trifft überhaupt nicht zu",
                      "Trifft nicht zu",
                      "Trifft eher nicht zu",
                      "Trifft eher zu",
                      "Trifft zu",
                      "Trifft voll und ganz zu")

skala.education <- c("Kein Abschluss",
                     "Hauptschulabschluss",
                     "Realschulabschluss/Mittlere Reife",
                     "Fachabitur/Abitur",
                     "Berufsausbildung",
                     "Studienabschluss (Bachelor, Master, Magister, Diplom, Promotion, etc.")

skala.semdiff <- c("1",
                   "2",
                   "3",
                   "4",
                   "5")


```

#Skalenberechnung
```{r, Skalenberechnung}

raw.short$Ausbildung <- ordered(raw.short$Ausbildung, levels = skala.education)

raw.short$BigFive10_1 <- ordered(raw.short$BigFive10_1, levels = skala.zutreffen)
raw.short$BigFive10_2 <- ordered(raw.short$BigFive10_2, levels = skala.zutreffen)
raw.short$BigFive10_3 <- ordered(raw.short$BigFive10_3, levels = skala.zutreffen)
raw.short$BigFive10_4 <- ordered(raw.short$BigFive10_4, levels = skala.zutreffen)
raw.short$BigFive10_5 <- ordered(raw.short$BigFive10_5, levels = skala.zutreffen)
raw.short$BigFive10_6 <- ordered(raw.short$BigFive10_6, levels = skala.zutreffen)
raw.short$BigFive10_7 <- ordered(raw.short$BigFive10_7, levels = skala.zutreffen)
raw.short$BigFive10_8 <- ordered(raw.short$BigFive10_8, levels = skala.zutreffen)
raw.short$BigFive10_9 <- ordered(raw.short$BigFive10_9, levels = skala.zutreffen)
raw.short$BigFive10_10 <- ordered(raw.short$BigFive10_10, levels = skala.zutreffen)

raw.short$InternetSkillScale_1 <-ordered (raw.short$InternetSkillScale_1, levels = skala.zutreffen)
raw.short$InternetSkillScale_2 <-ordered (raw.short$InternetSkillScale_2, levels = skala.zutreffen)
raw.short$InternetSkillScale_3 <-ordered (raw.short$InternetSkillScale_3, levels = skala.zutreffen)
raw.short$InternetSkillScale_4 <-ordered (raw.short$InternetSkillScale_4, levels = skala.zutreffen)
raw.short$InternetSkillScale_5 <-ordered (raw.short$InternetSkillScale_5, levels = skala.zutreffen)
raw.short$InternetSkillScale_6 <-ordered (raw.short$InternetSkillScale_6, levels = skala.zutreffen)
raw.short$InternetSkillScale_7 <-ordered (raw.short$InternetSkillScale_7, levels = skala.zutreffen)
raw.short$InternetSkillScale_8 <-ordered (raw.short$InternetSkillScale_8, levels = skala.zutreffen)

raw.short$Schlagzeile1SemDiff_1 <- ordered (raw.short$Schlagzeile1SemDiff_1, levels = skala.semdiff)
raw.short$Schlagzeile1SemDiff_2 <- ordered (raw.short$Schlagzeile1SemDiff_2, levels = skala.semdiff)
raw.short$Schlagzeile1SemDiff_3 <- ordered (raw.short$Schlagzeile1SemDiff_3, levels = skala.semdiff)
raw.short$Schlagzeile1SemDiff_4 <- ordered (raw.short$Schlagzeile1SemDiff_4, levels = skala.semdiff)
raw.short$Schlagzeile1SemDiff_5 <- ordered (raw.short$Schlagzeile1SemDiff_5, levels = skala.semdiff)
raw.short$Schlagzeile1SemDiff_6 <- ordered (raw.short$Schlagzeile1SemDiff_6, levels = skala.semdiff)
raw.short$Schlagzeile1SemDiff_7 <- ordered (raw.short$Schlagzeile1SemDiff_7, levels = skala.semdiff)

raw.short$Schlagzeile2SemDiff_1 <- ordered (raw.short$Schlagzeile2SemDiff_1, levels = skala.semdiff)
raw.short$Schlagzeile2SemDiff_2 <- ordered (raw.short$Schlagzeile2SemDiff_2, levels = skala.semdiff)
raw.short$Schlagzeile2SemDiff_3 <- ordered (raw.short$Schlagzeile2SemDiff_3, levels = skala.semdiff)
raw.short$Schlagzeile2SemDiff_4 <- ordered (raw.short$Schlagzeile2SemDiff_4, levels = skala.semdiff)
raw.short$Schlagzeile2SemDiff_5 <- ordered (raw.short$Schlagzeile2SemDiff_5, levels = skala.semdiff)
raw.short$Schlagzeile2SemDiff_6 <- ordered (raw.short$Schlagzeile2SemDiff_6, levels = skala.semdiff)
raw.short$Schlagzeile2SemDiff_7 <- ordered (raw.short$Schlagzeile2SemDiff_7, levels = skala.semdiff)

raw.short$Schlagzeile3SemDiff_1 <- ordered (raw.short$Schlagzeile3SemDiff_1, levels = skala.semdiff)
raw.short$Schlagzeile3SemDiff_2 <- ordered (raw.short$Schlagzeile3SemDiff_2, levels = skala.semdiff)
raw.short$Schlagzeile3SemDiff_3 <- ordered (raw.short$Schlagzeile3SemDiff_3, levels = skala.semdiff)
raw.short$Schlagzeile3SemDiff_4 <- ordered (raw.short$Schlagzeile3SemDiff_4, levels = skala.semdiff)
raw.short$Schlagzeile3SemDiff_5 <- ordered (raw.short$Schlagzeile3SemDiff_5, levels = skala.semdiff)
raw.short$Schlagzeile3SemDiff_6 <- ordered (raw.short$Schlagzeile3SemDiff_6, levels = skala.semdiff)
raw.short$Schlagzeile3SemDiff_7 <- ordered (raw.short$Schlagzeile3SemDiff_7, levels = skala.semdiff)

raw.short$Schlagzeile4SemDiff_1 <- ordered (raw.short$Schlagzeile4SemDiff_1, levels = skala.semdiff)
raw.short$Schlagzeile4SemDiff_2 <- ordered (raw.short$Schlagzeile4SemDiff_2, levels = skala.semdiff)
raw.short$Schlagzeile4SemDiff_3 <- ordered (raw.short$Schlagzeile4SemDiff_3, levels = skala.semdiff)
raw.short$Schlagzeile4SemDiff_4 <- ordered (raw.short$Schlagzeile4SemDiff_4, levels = skala.semdiff)
raw.short$Schlagzeile4SemDiff_5 <- ordered (raw.short$Schlagzeile4SemDiff_5, levels = skala.semdiff)
raw.short$Schlagzeile4SemDiff_6 <- ordered (raw.short$Schlagzeile4SemDiff_6, levels = skala.semdiff)
raw.short$Schlagzeile4SemDiff_7 <- ordered (raw.short$Schlagzeile4SemDiff_7, levels = skala.semdiff)

raw.short$Schlagzeile5SemDiff_1 <- ordered (raw.short$Schlagzeile5SemDiff_1, levels = skala.semdiff)
raw.short$Schlagzeile5SemDiff_2 <- ordered (raw.short$Schlagzeile5SemDiff_2, levels = skala.semdiff)
raw.short$Schlagzeile5SemDiff_3 <- ordered (raw.short$Schlagzeile5SemDiff_3, levels = skala.semdiff)
raw.short$Schlagzeile5SemDiff_4 <- ordered (raw.short$Schlagzeile5SemDiff_4, levels = skala.semdiff)
raw.short$Schlagzeile5SemDiff_5 <- ordered (raw.short$Schlagzeile5SemDiff_5, levels = skala.semdiff)
raw.short$Schlagzeile5SemDiff_6 <- ordered (raw.short$Schlagzeile5SemDiff_6, levels = skala.semdiff)
raw.short$Schlagzeile5SemDiff_7 <- ordered (raw.short$Schlagzeile5SemDiff_7, levels = skala.semdiff)

raw.short$Schlagzeile6SemDiff_1 <- ordered (raw.short$Schlagzeile6SemDiff_1, levels = skala.semdiff)
raw.short$Schlagzeile6SemDiff_2 <- ordered (raw.short$Schlagzeile6SemDiff_2, levels = skala.semdiff)
raw.short$Schlagzeile6SemDiff_3 <- ordered (raw.short$Schlagzeile6SemDiff_3, levels = skala.semdiff)
raw.short$Schlagzeile6SemDiff_4 <- ordered (raw.short$Schlagzeile6SemDiff_4, levels = skala.semdiff)
raw.short$Schlagzeile6SemDiff_5 <- ordered (raw.short$Schlagzeile6SemDiff_5, levels = skala.semdiff)
raw.short$Schlagzeile6SemDiff_6 <- ordered (raw.short$Schlagzeile6SemDiff_6, levels = skala.semdiff)
raw.short$Schlagzeile6SemDiff_7 <- ordered (raw.short$Schlagzeile6SemDiff_7, levels = skala.semdiff)

raw.short$Schlagzeile7SemDiff_1 <- ordered (raw.short$Schlagzeile7SemDiff_1, levels = skala.semdiff)
raw.short$Schlagzeile7SemDiff_2 <- ordered (raw.short$Schlagzeile7SemDiff_2, levels = skala.semdiff)
raw.short$Schlagzeile7SemDiff_3 <- ordered (raw.short$Schlagzeile7SemDiff_3, levels = skala.semdiff)
raw.short$Schlagzeile7SemDiff_4 <- ordered (raw.short$Schlagzeile7SemDiff_4, levels = skala.semdiff)
raw.short$Schlagzeile7SemDiff_5 <- ordered (raw.short$Schlagzeile7SemDiff_5, levels = skala.semdiff)
raw.short$Schlagzeile7SemDiff_6 <- ordered (raw.short$Schlagzeile7SemDiff_6, levels = skala.semdiff)
raw.short$Schlagzeile7SemDiff_7 <- ordered (raw.short$Schlagzeile7SemDiff_7, levels = skala.semdiff)

raw.short$Schlagzeile8SemDiff_1 <- ordered (raw.short$Schlagzeile8SemDiff_1, levels = skala.semdiff)
raw.short$Schlagzeile8SemDiff_2 <- ordered (raw.short$Schlagzeile8SemDiff_2, levels = skala.semdiff)
raw.short$Schlagzeile8SemDiff_3 <- ordered (raw.short$Schlagzeile8SemDiff_3, levels = skala.semdiff)
raw.short$Schlagzeile8SemDiff_4 <- ordered (raw.short$Schlagzeile8SemDiff_4, levels = skala.semdiff)
raw.short$Schlagzeile8SemDiff_5 <- ordered (raw.short$Schlagzeile8SemDiff_5, levels = skala.semdiff)
raw.short$Schlagzeile8SemDiff_6 <- ordered (raw.short$Schlagzeile8SemDiff_6, levels = skala.semdiff)
raw.short$Schlagzeile8SemDiff_7 <- ordered (raw.short$Schlagzeile8SemDiff_7, levels = skala.semdiff)

raw.short$Schlagzeile9SemDiff_1 <- ordered (raw.short$Schlagzeile9SemDiff_1, levels = skala.semdiff)
raw.short$Schlagzeile9SemDiff_2 <- ordered (raw.short$Schlagzeile9SemDiff_2, levels = skala.semdiff)
raw.short$Schlagzeile9SemDiff_3 <- ordered (raw.short$Schlagzeile9SemDiff_3, levels = skala.semdiff)
raw.short$Schlagzeile9SemDiff_4 <- ordered (raw.short$Schlagzeile9SemDiff_4, levels = skala.semdiff)
raw.short$Schlagzeile9SemDiff_5 <- ordered (raw.short$Schlagzeile9SemDiff_5, levels = skala.semdiff)
raw.short$Schlagzeile9SemDiff_6 <- ordered (raw.short$Schlagzeile9SemDiff_6, levels = skala.semdiff)
raw.short$Schlagzeile9SemDiff_7 <- ordered (raw.short$Schlagzeile9SemDiff_7, levels = skala.semdiff)

raw.short$Schlagzeile10SemDiff_1 <- ordered (raw.short$Schlagzeile10SemDiff_1, levels = skala.semdiff)
raw.short$Schlagzeile10SemDiff_2 <- ordered (raw.short$Schlagzeile10SemDiff_2, levels = skala.semdiff)
raw.short$Schlagzeile10SemDiff_3 <- ordered (raw.short$Schlagzeile10SemDiff_3, levels = skala.semdiff)
raw.short$Schlagzeile10SemDiff_4 <- ordered (raw.short$Schlagzeile10SemDiff_4, levels = skala.semdiff)
raw.short$Schlagzeile10SemDiff_5 <- ordered (raw.short$Schlagzeile10SemDiff_5, levels = skala.semdiff)
raw.short$Schlagzeile10SemDiff_6 <- ordered (raw.short$Schlagzeile10SemDiff_6, levels = skala.semdiff)
raw.short$Schlagzeile10SemDiff_7 <- ordered (raw.short$Schlagzeile10SemDiff_7, levels = skala.semdiff)

raw.short$Schlagzeile11SemDiff_1 <- ordered (raw.short$Schlagzeile11SemDiff_1, levels = skala.semdiff)
raw.short$Schlagzeile11SemDiff_2 <- ordered (raw.short$Schlagzeile11SemDiff_2, levels = skala.semdiff)
raw.short$Schlagzeile11SemDiff_3 <- ordered (raw.short$Schlagzeile11SemDiff_3, levels = skala.semdiff)
raw.short$Schlagzeile11SemDiff_4 <- ordered (raw.short$Schlagzeile11SemDiff_4, levels = skala.semdiff)
raw.short$Schlagzeile11SemDiff_5 <- ordered (raw.short$Schlagzeile11SemDiff_5, levels = skala.semdiff)
raw.short$Schlagzeile11SemDiff_6 <- ordered (raw.short$Schlagzeile11SemDiff_6, levels = skala.semdiff)
raw.short$Schlagzeile11SemDiff_7 <- ordered (raw.short$Schlagzeile11SemDiff_7, levels = skala.semdiff)

raw.short$Schlagzeile12SemDiff_1 <- ordered (raw.short$Schlagzeile12SemDiff_1, levels = skala.semdiff)
raw.short$Schlagzeile12SemDiff_2 <- ordered (raw.short$Schlagzeile12SemDiff_2, levels = skala.semdiff)
raw.short$Schlagzeile12SemDiff_3 <- ordered (raw.short$Schlagzeile12SemDiff_3, levels = skala.semdiff)
raw.short$Schlagzeile12SemDiff_4 <- ordered (raw.short$Schlagzeile12SemDiff_4, levels = skala.semdiff)
raw.short$Schlagzeile12SemDiff_5 <- ordered (raw.short$Schlagzeile12SemDiff_5, levels = skala.semdiff)
raw.short$Schlagzeile12SemDiff_6 <- ordered (raw.short$Schlagzeile12SemDiff_6, levels = skala.semdiff)
raw.short$Schlagzeile12SemDiff_7 <- ordered (raw.short$Schlagzeile12SemDiff_7, levels = skala.semdiff)
```


#Faktorenberechnung

```{r bfi_10, skillscale}
raw.short %>% select(starts_with("BigFive10")) %>%  get_label()

bfi_keys <- list(bfi_o = c("-BigFive10_5", "BigFive10_10"),
                 bfi_c = c("-BigFive10_3","BigFive10_8"),
                 bfi_e = c("-BigFive10_1", "BigFive10_6"),
                 bfi_a = c("BigFive10_2","-BigFive10_7"),
                 bfi_n = c("-BigFive10_4", "BigFive10_9"))

psych::scoreItems(bfi_keys, raw.short, impute = "median", min = 1, max =6)


raw.short %>% select(starts_with("InternetSkillScale")) %>%  get_label()

skill_keys <- list(skills = c("InternetSkillScale_1", 
                              "InternetSkillScale_2", 
                              "InternetSkillScale_3", 
                              "InternetSkillScale_4", 
                              "InternetSkillScale_5", 
                              "-InternetSkillScale_6", 
                              "-InternetSkillScale_7", 
                              "-InternetSkillScale_8"))

psych::scoreItems(skill_keys, raw.short, impute ="median", min = 1, max = 6)


headline_keys <- list( head_1 = c("Schlagzeile1SemDiff_1", "Schlagzeile1SemDiff_2", "Schlagzeile1SemDiff_3", "Schlagzeile1SemDiff_4", "Schlagzeile1SemDiff_5", "Schlagzeile1SemDiff_6", "Schlagzeile1SemDiff_7"),
                       head_2 = c("Schlagzeile2SemDiff_1", "Schlagzeile2SemDiff_2", "Schlagzeile2SemDiff_3", "Schlagzeile2SemDiff_4", "Schlagzeile2SemDiff_5", "Schlagzeile2SemDiff_6", "Schlagzeile2SemDiff_7"),
                       head_3 = c("Schlagzeile3SemDiff_1", "Schlagzeile3SemDiff_2", "Schlagzeile3SemDiff_3", "Schlagzeile3SemDiff_4", "Schlagzeile3SemDiff_5", "Schlagzeile3SemDiff_6", "Schlagzeile3SemDiff_7"),
                       head_4 = c("Schlagzeile4SemDiff_1", "Schlagzeile4SemDiff_2", "Schlagzeile4SemDiff_3", "Schlagzeile4SemDiff_4", "Schlagzeile4SemDiff_5", "Schlagzeile4SemDiff_6", "Schlagzeile4SemDiff_7"),
                       head_5 =c("Schlagzeile5SemDiff_1", "Schlagzeile5SemDiff_2", "Schlagzeile5SemDiff_3", "Schlagzeile5SemDiff_4", "Schlagzeile5SemDiff_5", "Schlagzeile5SemDiff_6", "Schlagzeile5SemDiff_7"),
                       head_6 = c("Schlagzeile6SemDiff_1", "Schlagzeile6SemDiff_2", "Schlagzeile6SemDiff_3", "Schlagzeile6SemDiff_4", "Schlagzeile6SemDiff_5", "Schlagzeile6SemDiff_6", "Schlagzeile6SemDiff_7"),
                       head_7 = c("Schlagzeile7SemDiff_1", "Schlagzeile7SemDiff_2", "Schlagzeile7SemDiff_3", "Schlagzeile7SemDiff_4", "Schlagzeile7SemDiff_5", "Schlagzeile7SemDiff_6", "Schlagzeile7SemDiff_7"),
                       head_8 = c("Schlagzeile8SemDiff_1", "Schlagzeile8SemDiff_2", "Schlagzeile8SemDiff_3", "Schlagzeile8SemDiff_4", "Schlagzeile8SemDiff_5", "Schlagzeile8SemDiff_6", "Schlagzeile8SemDiff_7"),
                       head_9 = c("Schlagzeile9SemDiff_1", "Schlagzeile9SemDiff_2", "Schlagzeile9SemDiff_3", "Schlagzeile9SemDiff_4", "Schlagzeile9SemDiff_5", "Schlagzeile9SemDiff_6", "Schlagzeile9SemDiff_7"),
                       head_10 = c("Schlagzeile10SemDiff_1", "Schlagzeile10SemDiff_2", "Schlagzeile10SemDiff_3", "Schlagzeile10SemDiff_4", "Schlagzeile10SemDiff_5", "Schlagzeile10SemDiff_6", "Schlagzeile10SemDiff_7"),
                       head_11 = c("Schlagzeile11SemDiff_1", "Schlagzeile11SemDiff_2", "Schlagzeile11SemDiff_3", "Schlagzeile11SemDiff_4", "Schlagzeile11SemDiff_5", "Schlagzeile11SemDiff_6", "Schlagzeile11SemDiff_7"),
                       head_12 = c("Schlagzeile12SemDiff_1", "Schlagzeile12SemDiff_2", "Schlagzeile12SemDiff_3", "Schlagzeile12SemDiff_4", "Schlagzeile12SemDiff_5", "Schlagzeile12SemDiff_6", "Schlagzeile12SemDiff_7"))


psych::scoreItems(headline_keys, raw.short, impute = "median", min = 1, max = 5)

```

```{r Tribble Data}

#Schlagzeile 1

df1 <- tibble::tribble(
  ~Personen, ~head_1, ~sz1_sd1, ~sz1_sd2, ~sz1_sd3, ~sz1_sd4, ~sz1_sd5, ~sz1_sd6, ~sz1_sd7,
          1,       0,        1,        2,        3,        3,        2,        2,        1,
          2,       1,        2,        2,        2,        2,        3,        2,        2,
          3,       1,        1,        1,        1,        1,        3,        2,        1,
          4,       1,        2,        3,        3,        2,        2,        2,        2,
          5,       0,        2,        3,        3,        2,        1,        3,        2,
          6,       1,        2,        4,        4,        2,        2,        1,        2,
          7,       1,        3,        3,        3,        3,        3,        4,        4,
          8,       1,        2,        3,        2,        2,        3,        2,        2,
          9,       1,        2,        2,        3,        2,        2,        2,        1,
         10,       0,        3,        3,        5,        2,        4,        5,        4,
         11,       1,        2,        2,        3,        3,        2,        1,        2,
         12,       1,        1,        1,        1,        1,        2,        1,        1,
         13,       0,        2,        1,        2,        2,        2,        1,        1,
         14,       1,        2,        3,        3,        3,        4,        2,        3,
         15,       1,        2,        3,        2,        4,        4,        2,        3,
         16,       1,        2,        2,        2,        3,        3,        2,        2,
         17,       1,        1,        1,        1,        2,        2,        1,        1,
         18,       0,        5,        5,        5,        1,        1,        5,        5,
         19,       1,        2,        3,        3,        2,        2,        1,        1,
         20,       1,        1,        2,        2,        1,        1,        2,        1,
         21,       0,        1,        2,        2,        1,        2,        2,        2,
         22,       0,        1,        1,        1,        1,        1,        2,        1,
         23,       1,        2,        2,        2,        2,        2,        2,        2,
         24,       1,        2,        2,        1,        2,        2,        3,        2,
         25,       1,        1,        2,        2,        1,        1,        2,        1,
         26,       1,        3,        3,        2,        1,        2,        4,        1,
         27,       0,        2,        2,        2,        2,        2,        2,        2,
         28,       1,        3,        4,        3,        3,        4,        3,        3,
         29,       1,        3,        2,        2,        1,        1,        1,        1,
         30,       0,        1,        3,        3,        3,        3,        1,        1,
         31,       1,        3,        3,        4,        2,        2,        2,        2,
         32,       1,        1,        1,        1,        1,        3,        1,        1,
         33,       1,        2,        4,        4,        3,        4,        2,        3,
         34,       0,        3,        3,        4,        3,        4,        3,        3,
         35,       1,        4,        2,        3,        3,        3,        3,        1,
         36,       0,        5,        4,        3,        4,        4,        4,        4,
         37,       1,        3,        3,        3,        4,        4,        4,        4,
         38,       1,        4,        3,        5,        3,        2,        3,        2,
         39,       0,        2,        3,        3,        2,        3,        2,        2,
         40,       1,        3,        3,        3,        4,        2,        2,        2,
         41,       1,        3,        3,        5,        3,        3,        2,        3,
         42,       1,        2,        3,        3,        2,        2,        2,        2,
         43,       1,        4,        4,        3,        2,        2,        3,        3,
         44,       1,        2,        2,        2,        1,        1,        1,        2,
         45,       1,        1,        2,        3,        2,        1,        3,        1,
         46,       0,        1,        3,        3,        2,        2,        2,        2,
         47,       1,        2,        2,        3,        1,        1,        2,        2,
         48,       1,        2,        4,        2,        2,        3,        3,        3,
         49,       1,        2,        2,        3,        2,        3,        2,        1,
         50,       1,        2,        2,        3,        2,        2,        2,        2,
         51,       1,        1,        4,        2,        1,        1,        2,        1,
         52,       1,        1,        2,        1,        1,        1,        1,        1,
         53,       1,        1,        1,        1,        1,        1,        1,        1,
         54,       1,        2,        1,        2,        3,        3,        2,        1,
         55,       1,        2,        3,        3,        5,        5,        5,        3,
         56,       0,        3,        4,        4,        2,        1,        3,        2,
         57,       1,        2,        1,        1,        3,        3,        1,        1,
         58,       0,        2,        2,        3,        2,        2,        3,        2,
         59,       1,        2,        2,        2,        2,        2,        2,        2,
         60,       1,        2,        3,        3,        2,        2,        2,        3,
         61,       1,        1,        1,        1,        2,        2,        2,        2,
         62,       0,        2,        2,        2,        2,        3,        3,        3,
         63,       0,        2,        4,        4,        2,        2,        4,        3,
         64,       1,        2,        3,        4,        4,        4,        2,        4,
         65,       1,        3,        4,        4,        2,        2,        3,        2,
         66,       1,        2,        3,        2,        2,        2,        2,        2,
         67,       1,        2,        2,        1,        2,        3,        2,        1,
         68,       1,        2,        4,        4,        2,        2,        3,        2,
         69,       0,        3,        3,        3,        1,        2,        5,        3,
         70,       1,        2,        4,        4,        2,        2,        3,        3,
         71,       0,        1,        1,        1,        3,        3,        2,        3,
         72,       0,        3,        2,        2,        2,        1,        2,        2,
         73,       0,        1,        1,        1,        2,        2,        2,        2,
         74,       1,        1,        3,        2,        3,        4,        2,        3,
         75,       1,        2,        2,        2,        2,        3,        2,        2,
         76,       1,        2,        2,        3,        2,        2,        3,        2,
         77,       1,        3,        4,        3,        2,        2,        2,        2,
         78,       1,        2,        2,        3,        2,        2,        2,        2,
         79,       0,        2,        2,        3,        2,        2,        4,        3,
         80,       1,        2,        2,        3,        2,        3,        2,        2,
         81,       1,        3,        3,        2,        1,        1,        3,        1,
         82,       1,        4,        5,        3,        3,        3,        4,        4,
         83,       0,        2,        2,        3,        3,        3,        2,        2,
         84,       1,        2,        4,        3,        2,        2,        3,        3,
         85,       0,        3,        4,        4,        3,        3,        2,        3,
         86,       0,        2,        2,        2,        1,        1,        4,        2,
         87,       1,        3,        4,        4,        3,        3,        3,        3,
         88,       1,        2,        3,        3,        2,        2,        3,        2,
         89,       0,        5,        4,        3,        2,        1,        2,        3,
         90,       0,        2,        3,        3,        1,        1,        2,        2,
         91,       1,        2,        2,        2,        3,        3,        2,        2,
         92,       1,        2,        3,        3,        2,        2,        2,        2,
         93,       1,        2,        3,        3,        2,        2,        4,        3,
         94,       0,        1,        1,        5,        1,        1,        1,        1,
         95,       1,        3,        3,        3,        3,        3,        5,        3,
         96,       1,        1,        1,        2,        1,        1,        2,        1,
         97,       1,        2,        3,        4,        1,        1,        1,        2,
         98,       1,        4,        4,        4,        3,        3,        2,        3,
         99,       1,        2,        3,        4,        1,        1,        2,        2,
        100,       1,        2,        3,        2,        1,        2,        2,        2,
        101,       0,        3,        3,        4,        3,        3,        2,        3,
        102,       1,        1,        2,        1,        1,        2,        1,        1,
        103,       1,        1,        3,        4,        2,        2,        2,        2,
        104,       1,        1,        3,        1,        1,        1,        1,        1,
        105,       1,        1,        1,        2,        2,        3,        1,        1,
        106,       0,        2,        3,        3,        2,        2,        3,        2,
        107,       1,        3,        4,        2,        2,        2,        3,        2,
        108,       1,        2,        2,        3,        1,        1,        1,        2,
        109,       0,        2,        2,        3,        2,        2,        1,        2,
        110,       1,        1,        2,        2,        2,        2,        1,        1,
        111,       1,        2,        4,        4,        2,        2,        2,        3,
        112,       0,        2,        4,        4,        2,        2,        2,        2,
        113,       1,        2,        3,        3,        1,        1,        2,        2,
        114,       1,        2,        3,        3,        2,        3,        2,        2,
        115,       1,        2,        2,        3,        3,        2,        2,        2,
        116,       1,        2,        3,        3,        2,        2,        2,        2,
        117,       1,        2,        3,        2,        3,        3,        1,        3,
        118,       1,        2,        2,        2,        1,        2,        1,        1,
        119,       1,        2,        3,        3,        2,        2,        1,        1,
        120,       0,        2,        2,        3,        2,        2,        2,        2,
        121,       1,        2,        3,        3,        3,        2,        2,        2,
        122,       1,        2,        2,        2,        2,        2,        2,        2,
        123,       1,        2,        3,        3,        2,        2,        2,        2
  )



# Schlagzeile 2

df2 <- tibble::tribble(
  ~Personen, ~head_2, ~sz2_sd1, ~sz2_sd2, ~sz2_sd3, ~sz2_sd4, ~sz2_sd5, ~sz2_sd6, ~sz2_sd7,
          1,       1,        1,        1,        1,        1,        1,        1,        1,
          2,       0,        2,        3,        2,        4,        4,        2,        2,
          3,       1,        3,        4,        4,        3,        4,        2,        3,
          4,       1,        5,        5,        5,        5,        5,        2,        4,
          5,       0,        3,        3,        4,        3,        3,        3,        4,
          6,       1,        4,        5,        5,        3,        5,        2,        4,
          7,       0,        3,        3,        3,        3,        3,        3,        3,
          8,       0,        2,        3,        2,        3,        3,        2,        3,
          9,       1,        3,        4,        4,        3,        4,        2,        3,
         10,       0,        3,        4,        5,        5,        2,        3,        5,
         11,       0,        3,        3,        3,        3,        3,        3,        3,
         12,       0,        2,        2,        2,        3,        3,        3,        2,
         13,       1,        2,        3,        3,        3,        2,        2,        2,
         14,       0,        2,        3,        2,        3,        3,        3,        3,
         15,       0,        5,        5,        4,        4,        5,        4,        4,
         16,       0,        3,        3,        4,        4,        4,        2,        4,
         17,       1,        4,        5,        5,        4,        4,        2,        4,
         18,       1,        5,        5,        5,        1,        1,        5,        5,
         19,       1,        3,        4,        5,        5,        4,        2,        4,
         20,       1,        2,        2,        1,        1,        1,        3,        1,
         21,       0,        2,        2,        2,        1,        3,        2,        2,
         22,       0,        2,        3,        4,        1,        1,        3,        3,
         23,       0,        2,        2,        2,        4,        4,        2,        2,
         24,       1,        4,        4,        3,        2,        2,        1,        3,
         25,       0,        4,        3,        1,        5,        4,        1,        3,
         26,       0,        3,        4,        4,        4,        4,        1,        2,
         27,       0,        2,        3,        2,        4,        4,        4,        3,
         28,       1,        4,        4,        4,        3,        3,        3,        3,
         29,       0,        2,        4,        4,        4,        4,        2,        3,
         30,       0,        3,        3,        1,        5,        2,        1,        3,
         31,       1,        3,        3,        4,        2,        2,        3,        1,
         32,       0,        2,        3,        2,        1,        3,        1,        3,
         33,       1,        2,        3,        2,        4,        3,        2,        3,
         34,       0,        3,        3,        3,        3,        3,        3,        3,
         35,       0,        1,        4,        5,        3,        1,        2,        3,
         36,       1,        4,        3,        4,        2,        1,        3,        1,
         37,       1,        5,        5,        5,        5,        1,        5,        5,
         38,       0,        4,        5,        5,        5,        4,        2,        3,
         39,       1,        2,        2,        3,        4,        4,        2,        3,
         40,       1,        5,        5,        4,        3,        4,        2,        2,
         41,       0,        4,        4,        4,        5,        3,        1,        3,
         42,       0,        5,        5,        5,        5,        5,        1,        2,
         43,       1,        5,        5,        5,        5,        5,        4,        4,
         44,       1,        3,        4,        5,        5,        3,        2,        4,
         45,       0,        3,        3,        3,        2,        4,        4,        2,
         46,       1,        4,        4,        4,        5,        4,        2,        4,
         47,       0,        4,        4,        4,        2,        2,        3,        2,
         48,       1,        4,        4,        3,        2,        3,        2,        4,
         49,       1,        2,        3,        4,        3,        4,        2,        3,
         50,       0,        4,        4,        4,        5,        4,        3,        3,
         51,       0,        2,        4,        4,        2,        2,        1,        2,
         52,       1,        4,        4,        5,        5,        4,        3,        4,
         53,       1,        1,        1,        1,        1,        1,        1,        3,
         54,       0,        5,        4,        4,        2,        2,        3,        3,
         55,       0,        5,        5,        5,        3,        3,        5,        5,
         56,       1,        5,        5,        5,        5,        5,        5,        5,
         57,       0,        3,        3,        3,        5,        4,        1,        1,
         58,       1,        4,        4,        3,        4,        3,        2,        4,
         59,       0,        3,        3,        3,        3,        3,        3,        3,
         60,       0,        4,        5,        4,        4,        2,        2,        4,
         61,       1,        2,        4,        4,        5,        5,        2,        3,
         62,       1,        4,        4,        4,        3,        3,        1,        1,
         63,       1,        4,        4,        4,        5,        4,        4,        3,
         64,       0,        4,        4,        4,        4,        4,        2,        4,
         65,       1,        4,        5,        5,        4,        4,        2,        3,
         66,       1,        4,        4,        4,        4,        3,        2,        3,
         67,       0,        2,        3,        3,        3,        2,        2,        1,
         68,       0,        2,        3,        4,        2,        2,        1,        2,
         69,       0,        5,        3,        4,        3,        1,        1,        4,
         70,       1,        3,        4,        5,        4,        4,        2,        3,
         71,       0,        1,        1,        1,        3,        3,        2,        2,
         72,       0,        3,        3,        3,        2,        3,        2,        2,
         73,       0,        3,        3,        3,        3,        3,        3,        3,
         74,       1,        1,        1,        1,        1,        3,        1,        1,
         75,       0,        2,        2,        2,        3,        3,        1,        2,
         76,       0,        2,        4,        4,        5,        4,        2,        3,
         77,       0,        1,        2,        3,        2,        4,        2,        2,
         78,       0,        4,        4,        4,        2,        2,        4,        3,
         79,       1,        2,        4,        4,        5,        4,        4,        4,
         80,       0,        1,        2,        2,        4,        3,        2,        2,
         81,       1,        4,        3,        4,        5,        4,        4,        4,
         82,       1,        4,        4,        4,        4,        4,        3,        5,
         83,       1,        4,        4,        3,        3,        3,        2,        3,
         84,       0,        4,        4,        4,        2,        3,        4,        3,
         85,       1,        4,        4,        4,        4,        4,        2,        4,
         86,       0,        4,        4,        3,        4,        5,        2,        3,
         87,       0,        4,        5,        5,        4,        4,        3,        5,
         88,       1,        2,        4,        4,        2,        2,        3,        3,
         89,       1,        3,        2,        3,        2,        3,        4,        3,
         90,       1,        5,        5,        5,        5,        5,        2,        5,
         91,       0,        2,        2,        2,        3,        3,        2,        2,
         92,       0,        4,        2,        3,        3,        2,        4,        2,
         93,       1,        2,        2,        2,        4,        3,        4,        3,
         94,       1,        1,        1,        4,        2,        2,        2,        2,
         95,       1,        4,        4,        3,        4,        3,        4,        3,
         96,       1,        2,        4,        5,        5,        2,        3,        4,
         97,       1,        3,        4,        5,        2,        2,        1,        4,
         98,       0,        4,        4,        4,        4,        4,        2,        3,
         99,       1,        2,        3,        2,        1,        1,        3,        2,
        100,       0,        4,        3,        4,        5,        5,        2,        5,
        101,       1,        5,        5,        5,        4,        4,        3,        3,
        102,       1,        2,        4,        3,        4,        3,        2,        3,
        103,       0,        3,        4,        4,        5,        4,        2,        3,
        104,       0,        2,        2,        3,        5,        4,        3,        2,
        105,       1,        2,        4,        4,        4,        3,        1,        2,
        106,       1,        4,        4,        4,        3,        2,        3,        2,
        107,       1,        3,        4,        4,        4,        3,        4,        4,
        108,       0,        4,        4,        5,        4,        4,        2,        3,
        109,       0,        1,        1,        1,        1,        1,        1,        1,
        110,       0,        3,        5,        5,        5,        5,        1,        3,
        111,       0,        5,        2,        4,        5,        5,        2,        4,
        112,       1,        4,        2,        4,        4,        1,        3,        3,
        113,       1,        5,        4,        4,        4,        2,        4,        3,
        114,       0,        2,        2,        3,        3,        4,        4,        3,
        115,       0,        3,        3,        4,        4,        4,        3,        2,
        116,       1,        2,        3,        3,        3,        4,        2,        3,
        117,       0,        2,        3,        3,        3,        2,        1,        2,
        118,       1,        4,        5,        5,        5,        5,        2,        4,
        119,       1,        4,        4,        3,        2,        2,        2,        3,
        120,       1,        3,        2,        3,        4,        3,        1,        3,
        121,       1,        4,        4,        5,        3,        4,        3,        3,
        122,       1,        3,        3,        3,        3,        3,        3,        2,
        123,       1,        5,        5,        5,        4,        4,        4,        4
  )

  
# Schlagzeile 3

df3 <- tibble::tribble(
  ~Personen, ~head_3, ~sz3_sd1, ~sz3_sd2, ~sz3_sd3, ~sz3_sd4, ~sz3_sd5, ~sz3_sd6, ~sz3_sd7,
          1,       0,        1,        3,        3,        2,        1,        1,        1,
          2,       1,        4,        4,        4,        4,        4,        2,        4,
          3,       0,        2,        3,        4,        3,        3,        2,        4,
          4,       1,        4,        5,        5,        5,        5,        5,        5,
          5,       0,        4,        4,        4,        5,        5,        3,        4,
          6,       1,        5,        5,        5,        5,        5,        5,        5,
          7,       0,        2,        2,        2,        2,        3,        2,        2,
          8,       1,        2,        3,        3,        3,        4,        3,        2,
          9,       0,        3,        5,        4,        5,        5,        2,        3,
         10,       0,        4,        4,        5,        5,        2,        4,        1,
         11,       1,        2,        3,        3,        4,        2,        1,        2,
         12,       1,        1,        1,        1,        1,        1,        1,        1,
         13,       1,        2,        2,        3,        2,        4,        2,        1,
         14,       0,        3,        3,        3,        2,        3,        3,        3,
         15,       1,        5,        5,        5,        5,        5,        3,        5,
         16,       0,        3,        3,        2,        2,        3,        2,        4,
         17,       0,        4,        5,        4,        5,        5,        2,        4,
         18,       0,        3,        4,        2,        4,        1,        5,        1,
         19,       0,        2,        5,        5,        4,        5,        2,        3,
         20,       1,        3,        3,        3,        3,        3,        3,        3,
         21,       0,        2,        2,        2,        4,        4,        2,        2,
         22,       1,        1,        2,        3,        4,        4,        2,        4,
         23,       0,        4,        4,        3,        4,        4,        4,        5,
         24,       0,        4,        5,        2,        4,        4,        3,        4,
         25,       0,        1,        2,        3,        1,        1,        2,        1,
         26,       1,        4,        4,        4,        4,        5,        3,        4,
         27,       1,        2,        2,        3,        5,        5,        1,        1,
         28,       1,        4,        4,        4,        5,        4,        3,        4,
         29,       0,        5,        5,        5,        5,        5,        2,        4,
         30,       0,        1,        5,        5,        5,        5,        1,        3,
         31,       0,        5,        5,        5,        3,        4,        2,        3,
         32,       1,        3,        2,        2,        1,        3,        5,        4,
         33,       1,        4,        4,        3,        4,        5,        4,        3,
         34,       0,        3,        3,        3,        3,        3,        3,        3,
         35,       1,        2,        4,        4,        1,        1,        2,        2,
         36,       1,        5,        4,        5,        3,        5,        3,        1,
         37,       1,        5,        5,        5,        5,        5,        5,        5,
         38,       1,        5,        4,        2,        3,        2,        2,        3,
         39,       1,        4,        2,        3,        4,        4,        5,        4,
         40,       1,        3,        2,        2,        2,        2,        2,        4,
         41,       1,        3,        4,        4,        5,        4,        1,        4,
         42,       1,        5,        5,        5,        5,        5,        3,        5,
         43,       1,        3,        3,        3,        3,        3,        4,        3,
         44,       1,        4,        4,        4,        5,        3,        2,        4,
         45,       1,        1,        1,        1,        1,        1,        3,        1,
         46,       1,        5,        5,        3,        4,        4,        3,        4,
         47,       0,        4,        4,        4,        4,        4,        3,        5,
         48,       1,        2,        2,        4,        4,        4,        2,        3,
         49,       0,        2,        3,        3,        2,        2,        2,        3,
         50,       1,        4,        4,        4,        4,        4,        4,        3,
         51,       1,        2,        4,        2,        4,        4,        1,        2,
         52,       1,        4,        5,        5,        3,        2,        4,        3,
         53,       0,        2,        2,        2,        2,        3,        3,        3,
         54,       0,        2,        3,        2,        4,        4,        2,        2,
         55,       1,        3,        5,        5,        4,        4,        4,        2,
         56,       1,        4,        4,        4,        3,        4,        3,        4,
         57,       0,        3,        2,        2,        4,        4,        3,        3,
         58,       0,        4,        5,        5,        4,        3,        2,        5,
         59,       1,        4,        4,        4,        2,        2,        4,        3,
         60,       1,        4,        4,        5,        4,        5,        2,        4,
         61,       0,        5,        4,        5,        5,        5,        5,        5,
         62,       1,        4,        5,        5,        5,        4,        2,        4,
         63,       1,        5,        5,        5,        5,        2,        5,        5,
         64,       0,        3,        4,        4,        4,        4,        2,        4,
         65,       0,        4,        5,        5,        4,        4,        4,        4,
         66,       1,        3,        4,        4,        4,        5,        2,        3,
         67,       0,        4,        2,        3,        4,        4,        4,        4,
         68,       0,        3,        2,        1,        1,        2,        3,        2,
         69,       0,        2,        2,        2,        4,        5,        3,        3,
         70,       0,        5,        4,        3,        5,        4,        3,        5,
         71,       0,        1,        1,        1,        4,        4,        2,        2,
         72,       1,        3,        3,        4,        2,        3,        2,        3,
         73,       0,        1,        1,        2,        3,        3,        2,        3,
         74,       0,        1,        1,        1,        3,        3,        3,        2,
         75,       0,        2,        4,        4,        2,        3,        2,        3,
         76,       0,        4,        4,        2,        5,        4,        3,        4,
         77,       1,        2,        2,        2,        2,        3,        4,        3,
         78,       0,        3,        3,        3,        4,        4,        3,        4,
         79,       0,        4,        5,        5,        5,        4,        4,        5,
         80,       0,        2,        4,        3,        3,        4,        3,        3,
         81,       0,        4,        2,        4,        3,        2,        1,        3,
         82,       1,        5,        5,        5,        5,        5,        4,        5,
         83,       0,        3,        2,        2,        2,        3,        3,        2,
         84,       0,        2,        4,        3,        5,        5,        2,        2,
         85,       0,        4,        4,        4,        4,        4,        2,        4,
         86,       1,        2,        2,        4,        4,        4,        2,        3,
         87,       0,        5,        5,        5,        5,        4,        5,        5,
         88,       0,        2,        3,        3,        2,        2,        3,        3,
         89,       0,        3,        3,        3,        3,        3,        3,        3,
         90,       0,        3,        4,        4,        5,        1,        4,        5,
         91,       1,        2,        2,        2,        3,        3,        3,        2,
         92,       1,        2,        4,        4,        4,        3,        2,        3,
         93,       1,        4,        4,        4,        4,        4,        3,        4,
         94,       1,        2,        5,        5,        3,        3,        2,        3,
         95,       1,        4,        4,        3,        5,        3,        5,        3,
         96,       1,        1,        2,        3,        5,        5,        1,        4,
         97,       0,        3,        5,        5,        5,        5,        2,        5,
         98,       1,        4,        4,        4,        5,        5,        4,        4,
         99,       0,        4,        5,        1,        4,        4,        5,        4,
        100,       1,        5,        5,        5,        5,        5,        3,        5,
        101,       0,        5,        5,        5,        5,        4,        4,        4,
        102,       1,        2,        2,        3,        4,        4,        3,        4,
        103,       0,        4,        3,        4,        5,        4,        4,        5,
        104,       0,        2,        3,        2,        4,        4,        2,        2,
        105,       1,        3,        4,        4,        5,        5,        2,        4,
        106,       0,        4,        4,        4,        4,        3,        3,        3,
        107,       1,        4,        4,        5,        4,        5,        5,        4,
        108,       0,        5,        5,        4,        5,        5,        2,        4,
        109,       0,        5,        5,        5,        5,        5,        5,        5,
        110,       0,        2,        5,        5,        5,        5,        1,        5,
        111,       1,        2,        2,        2,        5,        4,        5,        3,
        112,       1,        2,        2,        2,        4,        4,        2,        4,
        113,       1,        4,        4,        5,        5,        5,        3,        4,
        114,       1,        3,        4,        5,        4,        3,        3,        4,
        115,       0,        3,        2,        4,        4,        2,        2,        3,
        116,       0,        4,        4,        4,        5,        4,        5,        4,
        117,       1,        4,        5,        4,        4,        4,        3,        4,
        118,       0,        2,        4,        5,        5,        5,        3,        5,
        119,       0,        2,        3,        4,        3,        4,        3,        4,
        120,       1,        2,        3,        4,        3,        4,        2,        3,
        121,       0,        5,        5,        5,        4,        2,        2,        4,
        122,       1,        4,        5,        5,        5,        1,        5,        5,
        123,       0,        4,        5,        5,        4,        4,        5,        4
  )



#Schlagzeile 4

df4 <- tibble::tribble(
  ~Personen, ~head_4, ~sz4_sd1, ~sz4_sd2, ~sz4_sd13, ~sz4_sd4, ~sz4_sd5, ~sz4_sd6, ~sz4_sd7,
          1,       0,        2,        2,         3,        3,        2,        2,        2,
          2,       1,        2,        2,         2,        2,        2,        2,        2,
          3,       1,        2,        1,         1,        1,        2,        2,        1,
          4,       1,        2,        2,         1,        1,        1,        2,        1,
          5,       0,        4,        3,         4,        3,        3,        3,        3,
          6,       0,        3,        4,         4,        2,        2,        1,        2,
          7,       0,        3,        3,         5,        2,        4,        4,        2,
          8,       0,        2,        3,         2,        2,        3,        2,        3,
          9,       1,        3,        1,         2,        2,        3,        2,        2,
         10,       1,        3,        4,         3,        2,        5,        2,        1,
         11,       1,        3,        3,         2,        3,        4,        3,        2,
         12,       1,        1,        1,         1,        2,        2,        2,        1,
         13,       1,        1,        2,         1,        2,        3,        1,        1,
         14,       1,        2,        3,         3,        3,        3,        2,        3,
         15,       0,        2,        4,         4,        5,        4,        2,        3,
         16,       0,        3,        3,         2,        2,        2,        3,        3,
         17,       1,        2,        3,         3,        3,        2,        4,        3,
         18,       1,        5,        3,         2,        1,        1,        1,        1,
         19,       1,        1,        2,         2,        1,        3,        2,        1,
         20,       1,        1,        1,         1,        1,        1,        1,        1,
         21,       1,        2,        2,         4,        3,        3,        2,        2,
         22,       1,        2,        2,         2,        2,        2,        3,        2,
         23,       0,        2,        2,         2,        2,        3,        2,        2,
         24,       1,        1,        1,         1,        2,        2,        3,        2,
         25,       1,        1,        1,         1,        1,        1,        3,        1,
         26,       1,        1,        1,         1,        2,        2,        2,        2,
         27,       1,        2,        2,         2,        2,        2,        2,        2,
         28,       1,        4,        4,         4,        4,        4,        2,        3,
         29,       1,        1,        1,         1,        1,        2,        2,        1,
         30,       1,        1,        1,         1,        1,        1,        1,        1,
         31,       1,        1,        1,         1,        1,        2,        2,        1,
         32,       1,        1,        1,         1,        1,        1,        5,        1,
         33,       1,        2,        4,         3,        4,        3,        3,        2,
         34,       0,        2,        3,         3,        3,        3,        2,        3,
         35,       0,        3,        2,         2,        1,        1,        3,        2,
         36,       0,        5,        5,         3,        4,        2,        5,        1,
         37,       1,        2,        2,         2,        2,        2,        2,        2,
         38,       1,        3,        3,         2,        3,        4,        2,        3,
         39,       1,        2,        3,         4,        3,        2,        2,        4,
         40,       1,        2,        2,         2,        4,        4,        2,        2,
         41,       1,        2,        1,         1,        3,        2,        2,        3,
         42,       0,        1,        2,         2,        2,        2,        2,        2,
         43,       1,        1,        1,         1,        1,        1,        1,        1,
         44,       0,        2,        2,         2,        1,        2,        2,        2,
         45,       0,        1,        1,         3,        1,        1,        3,        3,
         46,       0,        2,        2,         2,        2,        2,        2,        2,
         47,       1,        2,        2,         2,        2,        2,        3,        2,
         48,       0,        2,        4,         4,        3,        3,        3,        3,
         49,       1,        1,        1,         1,        2,        2,        2,        1,
         50,       1,        2,        2,         2,        2,        2,        3,        2,
         51,       1,        1,        2,         1,        2,        1,        1,        1,
         52,       1,        1,        1,         1,        1,        1,        1,        1,
         53,       1,        1,        1,         1,        1,        1,        1,        1,
         54,       1,        2,        3,         4,        2,        2,        2,        4,
         55,       1,        4,        5,         5,        4,        4,        5,        4,
         56,       1,        1,        1,         1,        1,        1,        3,        1,
         57,       1,        2,        1,         1,        3,        3,        2,        1,
         58,       1,        2,        4,         4,        4,        5,        2,        5,
         59,       1,        2,        3,         2,        2,        2,        1,        2,
         60,       1,        2,        2,         2,        2,        2,        2,        2,
         61,       1,        1,        2,         2,        2,        3,        1,        1,
         62,       1,        1,        1,         1,        2,        2,        4,        2,
         63,       1,        2,        2,         3,        2,        2,        2,        2,
         64,       0,        3,        3,         4,        4,        4,        3,        4,
         65,       1,        2,        3,         4,        2,        2,        2,        2,
         66,       1,        2,        2,         2,        2,        2,        3,        2,
         67,       0,        3,        1,         2,        2,        1,        4,        2,
         68,       1,        1,        1,         1,        2,        1,        1,        1,
         69,       1,        3,        1,         1,        1,        1,        5,        3,
         70,       1,        2,        3,         2,        4,        4,        2,        2,
         71,       0,        2,        2,         2,        2,        3,        3,        3,
         72,       0,        2,        2,         3,        2,        1,        2,        2,
         73,       0,        2,        1,         1,        2,        1,        3,        2,
         74,       1,        2,        4,         4,        5,        3,        2,        4,
         75,       1,        1,        1,         1,        2,        2,        1,        1,
         76,       1,        2,        2,         2,        3,        2,        2,        2,
         77,       1,        1,        1,         2,        1,        1,        2,        1,
         78,       0,        2,        2,         2,        2,        2,        3,        2,
         79,       1,        2,        3,         2,        4,        4,        3,        4,
         80,       1,        2,        1,         1,        2,        2,        1,        1,
         81,       1,        2,        2,         2,        2,        2,        3,        1,
         82,       0,        4,        3,         3,        3,        3,        3,        3,
         83,       1,        3,        4,         3,        3,        4,        2,        3,
         84,       1,        2,        2,         2,        2,        2,        3,        2,
         85,       0,        2,        4,         4,        4,        3,        2,        4,
         86,       0,        3,        2,         4,        2,        2,        4,        3,
         87,       1,        3,        4,         4,        4,        3,        4,        4,
         88,       1,        2,        2,         2,        2,        2,        2,        3,
         89,       1,        1,        2,         3,        4,        5,        5,        5,
         90,       1,        1,        1,         1,        1,        1,        2,        2,
         91,       1,        2,        2,         2,        3,        3,        2,        2,
         92,       0,        2,        4,         4,        2,        2,        4,        2,
         93,       1,        2,        2,         2,        2,        2,        3,        2,
         94,       1,        1,        1,         1,        1,        2,        2,        2,
         95,       1,        3,        3,         3,        3,        3,        5,        3,
         96,       1,        1,        1,         1,        1,        1,        1,        1,
         97,       1,        2,        4,         5,        2,        2,        2,        3,
         98,       1,        2,        2,         2,        3,        3,        2,        2,
         99,       1,        2,        1,         1,        1,        3,        4,        2,
        100,       1,        1,        1,         1,        1,        1,        3,        1,
        101,       0,        4,        3,         3,        4,        2,        3,        2,
        102,       1,        2,        1,         1,        1,        2,        1,        1,
        103,       0,        2,        3,         2,        2,        2,        3,        2,
        104,       1,        1,        1,         1,        1,        1,        1,        1,
        105,       1,        2,        2,         3,        5,        4,        1,        2,
        106,       1,        2,        1,         1,        1,        1,        3,        1,
        107,       1,        2,        2,         3,        2,        2,        3,        2,
        108,       1,        1,        1,         1,        1,        1,        1,        1,
        109,       1,        3,        3,         3,        3,        3,        2,        4,
        110,       1,        1,        2,         2,        4,        2,        2,        2,
        111,       1,        2,        2,         2,        1,        1,        3,        2,
        112,       1,        1,        1,         1,        1,        1,        1,        1,
        113,       1,        2,        2,         1,        1,        2,        2,        1,
        114,       1,        2,        2,         1,        2,        2,        2,        1,
        115,       1,        2,        2,         3,        3,        3,        2,        2,
        116,       1,        2,        3,         3,        3,        2,        2,        2,
        117,       0,        4,        5,         4,        3,        3,        2,        3,
        118,       1,        2,        2,         1,        2,        1,        2,        2,
        119,       1,        1,        1,         1,        1,        1,        1,        1,
        120,       1,        2,        4,         3,        3,        3,        2,        3,
        121,       0,        2,        3,         4,        4,        4,        2,        3,
        122,       1,        3,        4,         4,        3,        3,        4,        4,
        123,       1,        2,        2,         2,        2,        2,        2,        2
  )

#Schlagzeile 5

df5 <- tibble::tribble(
  ~Personen, ~head_5, ~sz5_sd1, ~sz5_sd2, ~sz5_sd3, ~sz5_sd4, ~sz5_sd5, ~sz5_sd6, ~sz5_sd7,
          1,       0,        5,        3,        3,        3,        4,        5,        3,
          2,       0,        4,        4,        4,        4,        2,        3,        3,
          3,       0,        4,        4,        4,        3,        5,        5,        5,
          4,       0,        5,        4,        1,        4,        4,        5,        5,
          5,       0,        5,        5,        5,        5,        5,        5,        5,
          6,       0,        4,        2,        1,        3,        4,        5,        5,
          7,       0,        4,        3,        4,        4,        4,        4,        4,
          8,       0,        4,        4,        5,        3,        3,        5,        4,
          9,       0,        4,        5,        5,        5,        5,        4,        4,
         10,       0,        1,        1,        1,        1,        1,        1,        1,
         11,       0,        5,        4,        5,        3,        4,        5,        4,
         12,       1,        3,        3,        5,        3,        4,        3,        3,
         13,       0,        4,        2,        4,        3,        4,        3,        3,
         14,       0,        3,        4,        3,        2,        4,        3,        3,
         15,       0,        5,        2,        3,        5,        5,        5,        5,
         16,       0,        4,        4,        3,        3,        4,        5,        3,
         17,       0,        2,        5,        5,        5,        5,        5,        4,
         18,       0,        5,        5,        5,        5,        1,        5,        5,
         19,       0,        2,        1,        1,        3,        5,        3,        2,
         20,       1,        5,        5,        5,        5,        5,        5,        5,
         21,       0,        5,        5,        5,        1,        1,        5,        5,
         22,       0,        5,        3,        5,        4,        5,        5,        5,
         23,       0,        3,        4,        4,        3,        4,        4,        4,
         24,       0,        4,        5,        5,        4,        5,        3,        3,
         25,       0,        2,        1,        1,        5,        5,        5,        5,
         26,       0,        4,        4,        4,        5,        4,        5,        4,
         27,       0,        4,        4,        2,        5,        5,        1,        5,
         28,       0,        4,        4,        4,        3,        4,        4,        3,
         29,       0,        2,        5,        5,        5,        5,        2,        5,
         30,       0,        5,        5,        5,        5,        5,        5,        3,
         31,       0,        3,        5,        5,        3,        3,        5,        3,
         32,       0,        4,        3,        3,        3,        3,        5,        5,
         33,       0,        3,        3,        4,        5,        5,        4,        4,
         34,       0,        3,        3,        3,        3,        3,        3,        3,
         35,       0,        4,        4,        5,        3,        5,        3,        5,
         36,       0,        4,        2,        3,        4,        3,        2,        4,
         37,       0,        5,        5,        1,        1,        1,        5,        5,
         38,       0,        5,        5,        5,        3,        4,        5,        5,
         39,       0,        5,        2,        3,        4,        3,        5,        4,
         40,       0,        3,        2,        2,        4,        4,        5,        4,
         41,       0,        3,        2,        2,        1,        3,        5,        3,
         42,       0,        5,        5,        5,        4,        4,        5,        5,
         43,       0,        5,        5,        5,        4,        5,        5,        4,
         44,       0,        5,        4,        5,        4,        4,        5,        4,
         45,       0,        1,        1,        1,        4,        4,        5,        3,
         46,       0,        4,        2,        2,        3,        3,        4,        5,
         47,       0,        2,        2,        2,        2,        4,        4,        3,
         48,       1,        5,        3,        2,        4,        4,        2,        4,
         49,       0,        4,        3,        4,        4,        4,        4,        4,
         50,       0,        3,        3,        3,        4,        4,        4,        3,
         51,       0,        2,        2,        2,        4,        4,        2,        2,
         52,       0,        4,        5,        5,        4,        5,        5,        4,
         53,       0,        1,        1,        1,        1,        1,        1,        1,
         54,       0,        5,        4,        4,        2,        3,        5,        3,
         55,       0,        2,        4,        3,        1,        1,        1,        1,
         56,       0,        5,        5,        5,        5,        5,        5,        5,
         57,       0,        4,        4,        3,        4,        4,        2,        4,
         58,       1,        5,        5,        5,        5,        5,        5,        5,
         59,       0,        3,        3,        1,        1,        1,        5,        4,
         60,       0,        3,        3,        3,        4,        5,        5,        4,
         61,       0,        4,        5,        5,        5,        4,        5,        5,
         62,       0,        4,        4,        4,        4,        4,        5,        5,
         63,       0,        5,        5,        5,        5,        5,        5,        4,
         64,       0,        5,        1,        1,        5,        4,        5,        5,
         65,       0,        4,        4,        5,        4,        4,        5,        4,
         66,       0,        4,        4,        4,        3,        5,        4,        3,
         67,       0,        4,        1,        2,        3,        4,        4,        4,
         68,       0,        4,        2,        2,        5,        4,        5,        4,
         69,       0,        5,        5,        5,        5,        3,        5,        4,
         70,       0,        4,        4,        4,        3,        5,        5,        4,
         71,       0,        2,        2,        2,        3,        4,        5,        2,
         72,       0,        4,        4,        5,        3,        3,        3,        5,
         73,       0,        4,        4,        5,        3,        3,        4,        4,
         74,       0,        2,        2,        2,        4,        4,        5,        5,
         75,       0,        1,        2,        2,        3,        5,        3,        4,
         76,       0,        4,        4,        4,        5,        5,        5,        5,
         77,       0,        2,        4,        4,        4,        4,        1,        3,
         78,       1,        4,        4,        4,        4,        4,        3,        4,
         79,       0,        5,        5,        4,        4,        4,        5,        4,
         80,       0,        4,        4,        4,        5,        5,        5,        5,
         81,       0,        2,        1,        1,        3,        4,        5,        3,
         82,       0,        3,        3,        3,        3,        3,        3,        3,
         83,       0,        5,        5,        5,        4,        5,        3,        4,
         84,       0,        3,        4,        4,        2,        4,        5,        3,
         85,       0,        5,        5,        5,        5,        5,        4,        5,
         86,       0,        4,        4,        4,        3,        4,        4,        4,
         87,       0,        5,        5,        5,        5,        3,        5,        5,
         88,       0,        2,        2,        3,        1,        2,        2,        1,
         89,       0,        1,        2,        3,        5,        4,        3,        3,
         90,       0,        3,        5,        5,        4,        4,        5,        3,
         91,       0,        3,        1,        1,        3,        3,        5,        3,
         92,       0,        4,        2,        2,        4,        4,        4,        4,
         93,       0,        4,        4,        5,        4,        4,        5,        4,
         94,       0,        5,        2,        4,        5,        5,        5,        5,
         95,       0,        5,        5,        5,        5,        4,        5,        3,
         96,       0,        4,        5,        4,        5,        4,        3,        4,
         97,       0,        1,        1,        1,        5,        5,        2,        5,
         98,       0,        2,        2,        2,        4,        5,        5,        4,
         99,       0,        4,        5,        5,        3,        5,        4,        3,
        100,       0,        5,        4,        5,        5,        5,        5,        5,
        101,       0,        4,        5,        5,        5,        5,        5,        5,
        102,       0,        4,        3,        4,        4,        5,        4,        5,
        103,       0,        4,        3,        5,        4,        3,        5,        4,
        104,       0,        4,        3,        3,        5,        5,        5,        4,
        105,       0,        3,        2,        2,        4,        4,        4,        5,
        106,       0,        4,        4,        4,        5,        5,        4,        4,
        107,       0,        4,        4,        3,        4,        5,        5,        5,
        108,       0,        4,        4,        4,        5,        5,        4,        5,
        109,       0,        2,        2,        2,        1,        1,        4,        3,
        110,       0,        5,        5,        5,        4,        5,        5,        5,
        111,       0,        2,        2,        2,        4,        5,        5,        5,
        112,       0,        3,        2,        2,        4,        4,        2,        5,
        113,       0,        5,        5,        4,        4,        3,        5,        4,
        114,       0,        3,        2,        2,        4,        4,        3,        4,
        115,       0,        5,        5,        5,        4,        2,        5,        4,
        116,       0,        5,        2,        1,        5,        5,        5,        5,
        117,       0,        5,        5,        5,        3,        4,        5,        5,
        118,       0,        3,        4,        5,        4,        5,        5,        5,
        119,       0,        5,        4,        3,        4,        4,        5,        4,
        120,       0,        2,        2,        2,        4,        4,        2,        3,
        121,       0,        5,        5,        5,        2,        4,        4,        5,
        122,       0,        4,        4,        4,        5,        5,        5,        4,
        123,       0,        5,        5,        5,        5,        5,        4,        5
  )


# Schlagzeile 6

df6 <- tibble::tribble(
  ~Personen, ~head_6, ~sz6_sd1, ~sz6_sd2, ~sz6_sd3, ~sz6_sd4, ~sz6_sd5, ~sz6_sd6, ~sz6_sd7,
          1,       0,        5,        3,        4,        3,        2,        4,        2,
          2,       1,        2,        2,        3,        3,        2,        3,        3,
          3,       1,        2,        1,        2,        2,        3,        4,        3,
          4,       1,        2,        2,        1,        2,        2,        5,        2,
          5,       0,        4,        4,        4,        3,        3,        5,        4,
          6,       0,        3,        4,        4,        5,        5,        5,        4,
          7,       1,        3,        2,        3,        2,        2,        3,        3,
          8,       0,        3,        4,        2,        2,        2,        3,        2,
          9,       0,        3,        2,        2,        2,        3,        3,        2,
         10,       0,        5,        5,        5,        5,        5,        5,        5,
         11,       0,        3,        4,        4,        3,        4,        4,        3,
         12,       1,        3,        3,        3,        3,        4,        3,        3,
         13,       0,        3,        3,        3,        3,        4,        3,        2,
         14,       0,        3,        2,        3,        2,        4,        3,        3,
         15,       0,        5,        4,        3,        5,        5,        5,        5,
         16,       1,        2,        2,        2,        2,        4,        3,        4,
         17,       1,        2,        1,        1,        3,        3,        2,        2,
         18,       0,        1,        1,        1,        1,        1,        5,        5,
         19,       1,        2,        2,        1,        3,        4,        2,        1,
         20,       1,        3,        3,        3,        3,        3,        3,        3,
         21,       0,        5,        5,        5,        1,        1,        5,        3,
         22,       0,        5,        5,        5,        5,        5,        5,        5,
         23,       0,        4,        3,        2,        4,        4,        2,        3,
         24,       1,        1,        1,        1,        3,        4,        3,        3,
         25,       1,        2,        1,        1,        2,        1,        5,        1,
         26,       1,        2,        2,        2,        3,        3,        4,        3,
         27,       1,        2,        2,        2,        3,        3,        1,        5,
         28,       1,        4,        4,        4,        2,        2,        4,        3,
         29,       1,        1,        1,        1,        1,        3,        3,        1,
         30,       1,        3,        3,        3,        3,        3,        5,        3,
         31,       1,        2,        2,        4,        3,        4,        4,        3,
         32,       1,        3,        4,        3,        5,        4,        5,        4,
         33,       1,        4,        4,        4,        5,        4,        4,        3,
         34,       1,        2,        2,        2,        3,        3,        4,        3,
         35,       0,        2,        2,        2,        3,        5,        3,        4,
         36,       1,        4,        2,        3,        3,        4,        3,        3,
         37,       1,        3,        3,        1,        1,        1,        5,        3,
         38,       1,        4,        3,        2,        3,        2,        4,        3,
         39,       1,        5,        3,        2,        2,        2,        5,        3,
         40,       1,        2,        1,        2,        2,        2,        3,        2,
         41,       0,        3,        1,        1,        1,        3,        5,        3,
         42,       0,        2,        2,        2,        3,        3,        2,        3,
         43,       1,        1,        1,        1,        3,        1,        5,        1,
         44,       1,        1,        2,        2,        1,        1,        4,        1,
         45,       1,        1,        1,        1,        4,        4,        5,        2,
         46,       0,        5,        4,        3,        3,        4,        5,        5,
         47,       1,        4,        4,        3,        3,        3,        4,        4,
         48,       1,        4,        4,        4,        4,        4,        3,        3,
         49,       1,        1,        1,        1,        1,        2,        1,        1,
         50,       1,        2,        2,        2,        2,        2,        4,        2,
         51,       1,        2,        2,        2,        2,        2,        2,        2,
         52,       1,        1,        1,        1,        1,        1,        4,        1,
         53,       1,        1,        1,        1,        1,        1,        1,        1,
         54,       1,        2,        2,        2,        3,        4,        3,        2,
         55,       0,        4,        4,        3,        5,        3,        3,        4,
         56,       1,        3,        1,        1,        1,        1,        5,        5,
         57,       1,        1,        1,        1,        3,        2,        4,        3,
         58,       1,        2,        2,        2,        3,        4,        3,        2,
         59,       1,        3,        3,        1,        3,        1,        4,        4,
         60,       1,        3,        2,        2,        3,        4,        3,        3,
         61,       1,        5,        1,        2,        1,        3,        5,        1,
         62,       1,        2,        2,        2,        3,        3,        4,        3,
         63,       1,        2,        2,        2,        4,        3,        5,        4,
         64,       0,        2,        2,        2,        2,        2,        3,        3,
         65,       1,        3,        1,        1,        1,        3,        4,        2,
         66,       1,        4,        2,        2,        2,        3,        4,        3,
         67,       1,        3,        2,        3,        4,        3,        4,        3,
         68,       1,        2,        2,        2,        4,        4,        3,        3,
         69,       0,        1,        5,        3,        1,        5,        5,        5,
         70,       1,        2,        2,        3,        4,        3,        4,        2,
         71,       0,        2,        2,        2,        5,        5,        3,        2,
         72,       1,        1,        1,        1,        1,        2,        3,        3,
         73,       0,        1,        1,        1,        3,        3,        3,        4,
         74,       1,        1,        1,        1,        1,        3,        3,        1,
         75,       1,        1,        1,        1,        1,        2,        1,        2,
         76,       0,        3,        4,        2,        5,        4,        5,        4,
         77,       1,        3,        1,        1,        2,        2,        4,        2,
         78,       1,        2,        2,        2,        2,        2,        4,        2,
         79,       1,        5,        4,        2,        3,        2,        5,        3,
         80,       1,        2,        1,        1,        2,        4,        4,        3,
         81,       1,        3,        1,        1,        2,        4,        5,        4,
         82,       0,        3,        3,        3,        3,        3,        3,        3,
         83,       0,        3,        4,        4,        5,        3,        4,        4,
         84,       1,        2,        2,        1,        2,        3,        4,        2,
         85,       0,        5,        2,        2,        5,        4,        2,        4,
         86,       0,        2,        2,        2,        4,        2,        4,        4,
         87,       0,        5,        5,        5,        5,        3,        5,        5,
         88,       1,        4,        4,        4,        4,        5,        3,        3,
         89,       0,        1,        2,        3,        4,        5,        4,        2,
         90,       1,        3,        2,        2,        1,        1,        3,        3,
         91,       1,        2,        1,        1,        3,        3,        4,        3,
         92,       1,        4,        4,        3,        4,        3,        4,        4,
         93,       1,        2,        2,        2,        2,        2,        5,        2,
         94,       1,        3,        2,        3,        5,        5,        5,        5,
         95,       1,        5,        3,        3,        3,        2,        5,        3,
         96,       1,        3,        4,        1,        5,        2,        3,        4,
         97,       1,        1,        4,        5,        5,        5,        2,        5,
         98,       1,        2,        2,        2,        3,        5,        5,        3,
         99,       1,        3,        2,        2,        3,        4,        5,        2,
        100,       1,        1,        1,        1,        1,        1,        5,        2,
        101,       1,        3,        2,        3,        2,        2,        5,        3,
        102,       1,        2,        1,        1,        2,        2,        3,        3,
        103,       1,        2,        3,        2,        2,        2,        4,        3,
        104,       1,        2,        2,        2,        3,        3,        4,        3,
        105,       0,        4,        2,        2,        4,        4,        4,        4,
        106,       1,        1,        1,        1,        1,        2,        3,        2,
        107,       0,        3,        3,        4,        3,        2,        4,        4,
        108,       1,        2,        2,        1,        1,        2,        4,        3,
        109,       1,        2,        2,        2,        2,        2,        4,        3,
        110,       1,        1,        1,        1,        5,        5,        5,        3,
        111,       1,        4,        2,        2,        2,        5,        5,        4,
        112,       1,        2,        2,        2,        2,        2,        4,        4,
        113,       1,        2,        2,        1,        2,        2,        3,        2,
        114,       1,        2,        3,        1,        3,        3,        3,        3,
        115,       1,        2,        2,        2,        4,        1,        4,        4,
        116,       1,        5,        2,        1,        3,        3,        5,        3,
        117,       0,        4,        4,        3,        2,        4,        5,        5,
        118,       1,        3,        2,        2,        3,        2,        4,        4,
        119,       1,        3,        2,        1,        2,        2,        5,        3,
        120,       0,        2,        3,        3,        4,        4,        4,        3,
        121,       0,        2,        2,        3,        4,        4,        4,        5,
        122,       1,        3,        3,        3,        3,        3,        4,        4,
        123,       1,        3,        1,        1,        2,        2,        2,        2
  )


# Schlagzeile 7

df7 <- tibble::tribble(
  ~Personen, ~head_7, ~sz7_sd1, ~sz7_sd2, ~sz7_sd3, ~sz7_sd4, ~sz7_sd5, ~sz7_sd6, ~sz7_sd7,
          1,       1,        1,        1,        1,        2,        1,        1,        1,
          2,       1,        2,        2,        2,        3,        4,        4,        2,
          3,       1,        2,        3,        3,        4,        4,        2,        3,
          4,       0,        5,        5,        5,        5,        4,        3,        5,
          5,       0,        3,        4,        4,        4,        3,        3,        4,
          6,       0,        5,        5,        4,        5,        3,        1,        3,
          7,       1,        3,        3,        3,        3,        3,        3,        3,
          8,       1,        2,        1,        2,        2,        3,        2,        2,
          9,       1,        3,        4,        4,        4,        3,        2,        3,
         10,       0,        1,        2,        3,        4,        5,        4,        3,
         11,       0,        2,        2,        2,        3,        2,        3,        3,
         12,       1,        2,        3,        3,        2,        1,        4,        2,
         13,       1,        2,        2,        3,        3,        3,        2,        2,
         14,       1,        3,        3,        2,        3,        2,        3,        3,
         15,       1,        2,        2,        1,        3,        4,        3,        3,
         16,       1,        2,        3,        2,        4,        4,        1,        3,
         17,       1,        1,        2,        2,        3,        3,        2,        2,
         18,       1,        5,        5,        5,        1,        1,        4,        5,
         19,       1,        2,        1,        3,        4,        3,        1,        2,
         20,       1,        2,        2,        2,        4,        4,        2,        3,
         21,       1,        4,        1,        1,        3,        3,        2,        2,
         22,       1,        2,        4,        4,        3,        3,        3,        4,
         23,       1,        2,        2,        2,        3,        3,        2,        2,
         24,       1,        2,        4,        3,        2,        1,        3,        2,
         25,       1,        3,        2,        1,        3,        2,        2,        2,
         26,       0,        3,        3,        2,        4,        4,        4,        3,
         27,       1,        2,        2,        2,        3,        3,        2,        2,
         28,       1,        2,        2,        4,        4,        4,        2,        3,
         29,       1,        2,        2,        2,        3,        3,        2,        2,
         30,       1,        5,        5,        5,        3,        3,        1,        3,
         31,       1,        3,        4,        4,        3,        4,        2,        2,
         32,       1,        1,        1,        1,        1,        1,        1,        1,
         33,       1,        3,        2,        3,        3,        4,        2,        2,
         34,       1,        3,        3,        3,        3,        3,        3,        3,
         35,       1,        4,        4,        4,        3,        2,        2,        2,
         36,       0,        5,        2,        4,        2,        4,        3,        3,
         37,       1,        3,        3,        5,        5,        3,        4,        4,
         38,       1,        4,        3,        4,        3,        4,        3,        3,
         39,       1,        3,        2,        2,        3,        4,        2,        3,
         40,       1,        3,        4,        4,        2,        2,        2,        2,
         41,       1,        3,        3,        4,        4,        3,        2,        3,
         42,       0,        4,        4,        4,        3,        3,        2,        3,
         43,       0,        5,        5,        5,        5,        5,        5,        5,
         44,       1,        2,        3,        3,        2,        3,        5,        1,
         45,       1,        1,        1,        1,        1,        1,        5,        2,
         46,       0,        4,        2,        4,        3,        3,        2,        3,
         47,       0,        4,        4,        4,        4,        4,        2,        4,
         48,       0,        2,        2,        2,        1,        4,        2,        2,
         49,       1,        2,        2,        3,        3,        3,        2,        2,
         50,       0,        4,        4,        4,        2,        3,        2,        3,
         51,       1,        2,        4,        3,        2,        2,        3,        2,
         52,       0,        4,        5,        3,        2,        2,        3,        3,
         53,       1,        2,        3,        2,        2,        2,        4,        3,
         54,       1,        2,        4,        4,        2,        2,        2,        2,
         55,       1,        5,        4,        5,        3,        4,        5,        5,
         56,       1,        5,        4,        3,        4,        4,        5,        3,
         57,       1,        1,        1,        2,        4,        4,        2,        2,
         58,       1,        1,        1,        1,        2,        2,        1,        1,
         59,       1,        2,        2,        2,        1,        2,        4,        3,
         60,       1,        3,        4,        4,        3,        4,        3,        3,
         61,       1,        4,        4,        4,        5,        5,        5,        4,
         62,       1,        2,        2,        2,        3,        3,        3,        3,
         63,       1,        2,        3,        3,        4,        4,        4,        3,
         64,       1,        3,        3,        3,        3,        3,        2,        4,
         65,       0,        3,        4,        4,        4,        4,        3,        3,
         66,       0,        2,        5,        5,        4,        4,        3,        3,
         67,       0,        2,        2,        1,        2,        4,        2,        2,
         68,       1,        2,        2,        4,        2,        1,        3,        2,
         69,       0,        3,        1,        1,        1,        5,        1,        3,
         70,       1,        3,        2,        2,        4,        4,        4,        3,
         71,       0,        2,        2,        2,        3,        3,        3,        2,
         72,       1,        1,        2,        2,        2,        2,        2,        2,
         73,       0,        3,        3,        3,        3,        3,        3,        3,
         74,       1,        1,        1,        1,        1,        1,        1,        1,
         75,       1,        2,        4,        4,        3,        3,        3,        3,
         76,       1,        2,        4,        4,        2,        3,        3,        2,
         77,       1,        4,        5,        5,        5,        3,        2,        4,
         78,       1,        1,        1,        1,        2,        3,        3,        1,
         79,       1,        5,        5,        3,        5,        5,        5,        5,
         80,       1,        2,        4,        4,        5,        4,        3,        2,
         81,       0,        2,        4,        3,        4,        3,        2,        2,
         82,       1,        3,        3,        3,        3,        3,        3,        3,
         83,       1,        3,        3,        3,        3,        3,        4,        2,
         84,       1,        4,        3,        4,        4,        4,        4,        3,
         85,       1,        3,        4,        3,        4,        4,        2,        4,
         86,       1,        2,        2,        2,        5,        4,        2,        3,
         87,       0,        5,        5,        5,        5,        3,        2,        3,
         88,       1,        3,        2,        2,        3,        4,        4,        3,
         89,       1,        5,        4,        3,        2,        1,        2,        4,
         90,       1,        2,        4,        4,        4,        2,        2,        3,
         91,       1,        2,        2,        2,        3,        3,        2,        2,
         92,       0,        4,        4,        3,        2,        2,        2,        3,
         93,       1,        2,        3,        4,        4,        3,        4,        2,
         94,       0,        3,        3,        4,        4,        4,        4,        4,
         95,       1,        4,        4,        3,        4,        3,        5,        3,
         96,       1,        1,        2,        2,        4,        4,        2,        2,
         97,       1,        1,        4,        5,        4,        5,        1,        3,
         98,       1,        2,        3,        4,        4,        4,        2,        3,
         99,       0,        3,        4,        4,        2,        4,        3,        2,
        100,       1,        3,        5,        5,        4,        4,        4,        3,
        101,       1,        4,        4,        4,        4,        4,        3,        3,
        102,       1,        1,        2,        1,        2,        2,        1,        2,
        103,       1,        3,        2,        3,        4,        4,        4,        2,
        104,       0,        3,        2,        2,        5,        5,        3,        3,
        105,       0,        3,        4,        4,        5,        5,        2,        5,
        106,       1,        3,        4,        4,        2,        3,        3,        2,
        107,       1,        2,        2,        3,        4,        4,        3,        3,
        108,       1,        2,        3,        3,        2,        3,        2,        3,
        109,       0,        2,        1,        1,        1,        1,        1,        1,
        110,       0,        5,        5,        5,        5,        5,        4,        4,
        111,       1,        2,        2,        1,        2,        4,        1,        2,
        112,       1,        4,        4,        4,        2,        2,        3,        3,
        113,       0,        3,        3,        3,        1,        2,        3,        2,
        114,       1,        2,        2,        2,        2,        3,        2,        2,
        115,       1,        4,        4,        4,        4,        3,        3,        3,
        116,       1,        3,        2,        2,        4,        3,        3,        3,
        117,       0,        2,        2,        2,        3,        3,        1,        2,
        118,       1,        3,        2,        3,        5,        4,        2,        3,
        119,       1,        2,        1,        1,        4,        3,        2,        3,
        120,       0,        2,        2,        4,        3,        3,        3,        3,
        121,       0,        4,        5,        5,        4,        4,        2,        3,
        122,       0,        4,        4,        4,        3,        3,        4,        4,
        123,       1,        5,        5,        5,        4,        3,        3,        4
  )

# Schlagzeile 8

df8 <- tibble::tribble(
  ~Personen, ~head_8, ~sz8_sd1, ~sz8_sd2, ~sz8_sd3, ~sz8_sd4, ~sz8_sd5, ~sz8_sd6, ~sz8_sd7,
          1,       0,        1,        2,        1,        2,        1,        1,        1,
          2,       1,        3,        4,        4,        4,        4,        2,        3,
          3,       0,        2,        4,        4,        3,        3,        1,        2,
          4,       1,        4,        5,        5,        3,        2,        2,        3,
          5,       1,        2,        3,        3,        2,        2,        2,        3,
          6,       1,        2,        5,        4,        2,        4,        2,        4,
          7,       0,        2,        3,        2,        3,        2,        3,        2,
          8,       1,        4,        4,        3,        4,        2,        4,        4,
          9,       1,        3,        2,        3,        2,        3,        2,        2,
         10,       1,        5,        4,        3,        2,        1,        2,        3,
         11,       0,        2,        2,        2,        4,        5,        1,        2,
         12,       0,        2,        2,        2,        4,        3,        2,        3,
         13,       0,        2,        2,        3,        2,        2,        2,        2,
         14,       0,        3,        2,        2,        2,        3,        3,        3,
         15,       1,        4,        2,        4,        5,        4,        4,        5,
         16,       0,        3,        4,        3,        2,        2,        3,        5,
         17,       0,        1,        3,        3,        4,        4,        1,        2,
         18,       0,        5,        5,        5,        1,        1,        5,        5,
         19,       0,        1,        3,        2,        1,        2,        1,        1,
         20,       1,        3,        4,        4,        4,        4,        4,        2,
         21,       0,        3,        2,        2,        3,        3,        2,        3,
         22,       0,        4,        4,        4,        3,        3,        3,        4,
         23,       1,        4,        2,        3,        2,        2,        2,        2,
         24,       1,        4,        4,        2,        3,        2,        2,        3,
         25,       0,        5,        3,        2,        5,        2,        1,        4,
         26,       1,        2,        3,        4,        2,        2,        4,        3,
         27,       0,        3,        3,        3,        4,        4,        2,        3,
         28,       0,        4,        4,        4,        2,        2,        2,        3,
         29,       0,        2,        3,        3,        4,        4,        2,        3,
         30,       1,        5,        5,        5,        3,        3,        1,        1,
         31,       1,        2,        4,        4,        2,        2,        2,        2,
         32,       0,        1,        1,        1,        1,        1,        1,        1,
         33,       1,        3,        4,        3,        2,        3,        2,        3,
         34,       1,        3,        3,        3,        3,        3,        3,        3,
         35,       0,        3,        2,        2,        1,        1,        1,        1,
         36,       1,        4,        2,        4,        2,        3,        3,        3,
         37,       1,        5,        4,        4,        4,        4,        3,        3,
         38,       1,        2,        4,        4,        2,        2,        3,        3,
         39,       1,        2,        3,        4,        2,        3,        3,        2,
         40,       1,        3,        2,        4,        4,        2,        2,        2,
         41,       1,        2,        2,        2,        4,        3,        2,        4,
         42,       1,        4,        4,        4,        3,        3,        1,        2,
         43,       1,        3,        4,        2,        2,        1,        3,        3,
         44,       1,        4,        4,        4,        3,        1,        2,        3,
         45,       0,        1,        1,        1,        1,        1,        5,        3,
         46,       1,        5,        5,        4,        2,        3,        3,        3,
         47,       0,        3,        3,        4,        3,        2,        2,        3,
         48,       1,        2,        4,        4,        2,        2,        3,        4,
         49,       1,        2,        2,        4,        2,        3,        1,        2,
         50,       0,        4,        4,        4,        2,        4,        2,        3,
         51,       1,        2,        4,        2,        2,        2,        1,        2,
         52,       0,        2,        4,        4,        2,        2,        3,        3,
         53,       0,        2,        2,        3,        2,        2,        3,        3,
         54,       0,        1,        4,        4,        3,        3,        2,        2,
         55,       0,        1,        3,        4,        4,        4,        5,        2,
         56,       1,        5,        5,        5,        5,        1,        5,        5,
         57,       0,        3,        3,        3,        3,        3,        2,        2,
         58,       1,        3,        3,        2,        4,        4,        2,        3,
         59,       1,        2,        2,        2,        2,        2,        1,        3,
         60,       1,        4,        4,        4,        3,        3,        3,        4,
         61,       1,        1,        2,        2,        4,        4,        2,        2,
         62,       1,        3,        4,        4,        4,        3,        2,        3,
         63,       1,        2,        4,        4,        2,        2,        4,        3,
         64,       0,        3,        2,        2,        4,        3,        2,        2,
         65,       1,        3,        4,        3,        3,        3,        3,        3,
         66,       0,        3,        4,        4,        2,        2,        2,        3,
         67,       1,        1,        1,        2,        2,        3,        2,        2,
         68,       1,        4,        4,        5,        3,        1,        4,        3,
         69,       0,        5,        1,        3,        5,        5,        4,        3,
         70,       1,        4,        4,        2,        3,        4,        2,        3,
         71,       0,        2,        2,        2,        3,        3,        2,        3,
         72,       1,        2,        2,        3,        1,        1,        2,        2,
         73,       1,        3,        3,        3,        3,        3,        3,        3,
         74,       1,        1,        3,        3,        3,        3,        1,        1,
         75,       0,        3,        2,        2,        2,        2,        2,        3,
         76,       1,        2,        4,        3,        3,        2,        2,        4,
         77,       1,        3,        1,        4,        4,        4,        1,        4,
         78,       1,        4,        4,        3,        2,        3,        3,        3,
         79,       1,        2,        3,        3,        2,        2,        3,        3,
         80,       1,        2,        4,        4,        3,        2,        3,        2,
         81,       1,        2,        4,        5,        2,        2,        2,        2,
         82,       0,        2,        2,        2,        2,        2,        2,        2,
         83,       1,        3,        3,        2,        3,        3,        2,        3,
         84,       0,        2,        4,        4,        3,        3,        3,        3,
         85,       1,        3,        4,        4,        4,        5,        2,        4,
         86,       1,        4,        2,        4,        2,        2,        4,        4,
         87,       1,        3,        5,        5,        5,        1,        5,        5,
         88,       0,        3,        4,        4,        4,        4,        3,        3,
         89,       1,        1,        2,        4,        4,        2,        2,        2,
         90,       0,        3,        3,        3,        4,        4,        5,        3,
         91,       0,        2,        2,        2,        4,        3,        1,        2,
         92,       1,        2,        2,        2,        2,        3,        2,        2,
         93,       1,        3,        3,        4,        2,        2,        4,        3,
         94,       0,        2,        2,        3,        3,        3,        3,        3,
         95,       1,        4,        4,        3,        3,        3,        5,        3,
         96,       1,        1,        2,        2,        2,        3,        2,        4,
         97,       0,        2,        2,        4,        4,        4,        3,        5,
         98,       0,        3,        4,        4,        2,        2,        2,        3,
         99,       1,        2,        4,        4,        1,        1,        2,        3,
        100,       1,        3,        4,        5,        5,        4,        2,        4,
        101,       0,        3,        5,        5,        5,        4,        1,        3,
        102,       0,        3,        3,        2,        2,        1,        3,        3,
        103,       1,        5,        3,        4,        4,        3,        4,        4,
        104,       0,        1,        1,        2,        4,        4,        2,        2,
        105,       1,        2,        4,        4,        3,        3,        1,        2,
        106,       1,        4,        2,        3,        2,        5,        4,        2,
        107,       1,        4,        4,        4,        4,        3,        4,        4,
        108,       1,        3,        3,        4,        4,        2,        2,        4,
        109,       1,        3,        3,        3,        3,        3,        2,        4,
        110,       0,        1,        2,        2,        5,        4,        2,        2,
        111,       1,        2,        4,        2,        3,        3,        3,        3,
        112,       1,        2,        2,        2,        2,        2,        2,        2,
        113,       0,        2,        3,        3,        2,        2,        2,        2,
        114,       0,        2,        3,        3,        4,        4,        3,        3,
        115,       0,        3,        3,        4,        2,        1,        3,        2,
        116,       0,        2,        2,        2,        3,        3,        2,        3,
        117,       1,        2,        4,        3,        3,        3,        1,        3,
        118,       0,        2,        3,        3,        4,        3,        3,        4,
        119,       1,        4,        2,        2,        3,        1,        3,        3,
        120,       1,        4,        4,        4,        3,        2,        2,        3,
        121,       1,        2,        3,        3,        3,        4,        2,        3,
        122,       1,        4,        3,        3,        3,        3,        3,        3,
        123,       1,        3,        4,        4,        4,        4,        4,        4
  )

#Schlagzeile 9

df9 <- tibble::tribble(
  ~Personen, ~head_9, ~sz9_sd1, ~sz9_sd2, ~sz9_sd3, ~sz9_sd4, ~sz9_sd5, ~sz9_sd6, ~sz9_sd7,
          1,       1,        4,        3,        3,        4,        1,        5,        4,
          2,       1,        4,        4,        4,        2,        3,        3,        2,
          3,       1,        3,        2,        4,        4,        4,        3,        3,
          4,       1,        3,        4,        5,        4,        4,        3,        3,
          5,       0,        2,        2,        2,        3,        4,        4,        3,
          6,       1,        2,        1,        1,        2,        3,        4,        3,
          7,       1,        2,        2,        2,        2,        2,        2,        2,
          8,       1,        4,        3,        4,        4,        4,        2,        4,
          9,       1,        3,        4,        4,        5,        5,        3,        4,
         10,       0,        2,        2,        3,        3,        3,        4,        5,
         11,       1,        2,        2,        3,        2,        3,        4,        3,
         12,       0,        2,        2,        2,        3,        2,        3,        4,
         13,       1,        4,        4,        3,        4,        3,        4,        4,
         14,       1,        3,        2,        3,        3,        3,        3,        3,
         15,       0,        2,        4,        3,        5,        4,        3,        4,
         16,       1,        3,        4,        4,        2,        2,        3,        5,
         17,       1,        3,        4,        3,        2,        4,        3,        3,
         18,       0,        5,        4,        4,        3,        2,        5,        3,
         19,       1,        1,        2,        1,        2,        3,        2,        2,
         20,       1,        2,        2,        3,        2,        3,        2,        3,
         21,       1,        5,        4,        3,        3,        1,        3,        2,
         22,       1,        2,        1,        2,        3,        3,        2,        3,
         23,       1,        4,        2,        2,        3,        4,        2,        4,
         24,       1,        3,        1,        1,        5,        5,        5,        4,
         25,       1,        4,        2,        1,        4,        3,        1,        4,
         26,       1,        1,        1,        1,        2,        4,        2,        2,
         27,       1,        3,        4,        4,        2,        3,        1,        2,
         28,       1,        4,        2,        4,        3,        2,        4,        3,
         29,       1,        2,        2,        2,        1,        3,        2,        2,
         30,       0,        3,        3,        3,        1,        1,        5,        3,
         31,       1,        1,        2,        3,        1,        4,        2,        1,
         32,       1,        3,        1,        1,        1,        3,        5,        3,
         33,       1,        4,        3,        4,        5,        4,        4,        4,
         34,       0,        3,        3,        3,        3,        3,        3,        3,
         35,       1,        2,        3,        3,        3,        3,        3,        4,
         36,       0,        2,        3,        2,        4,        4,        3,        3,
         37,       1,        5,        3,        3,        5,        3,        5,        3,
         38,       0,        2,        1,        2,        3,        2,        5,        3,
         39,       0,        2,        2,        3,        2,        4,        2,        3,
         40,       1,        3,        4,        4,        4,        2,        4,        2,
         41,       1,        3,        1,        1,        1,        2,        5,        3,
         42,       0,        2,        2,        3,        3,        3,        2,        2,
         43,       1,        4,        4,        5,        3,        3,        4,        3,
         44,       1,        2,        2,        4,        2,        3,        2,        2,
         45,       1,        1,        1,        1,        4,        4,        5,        2,
         46,       0,        2,        4,        5,        4,        4,        2,        4,
         47,       0,        2,        3,        3,        3,        2,        4,        3,
         48,       0,        4,        4,        4,        3,        2,        4,        4,
         49,       1,        1,        2,        3,        1,        2,        2,        1,
         50,       1,        2,        1,        1,        4,        4,        2,        2,
         51,       1,        2,        1,        1,        1,        1,        2,        1,
         52,       1,        2,        2,        2,        2,        2,        3,        2,
         53,       1,        1,        1,        1,        1,        1,        1,        1,
         54,       1,        1,        2,        3,        4,        4,        2,        2,
         55,       1,        3,        4,        4,        5,        5,        3,        4,
         56,       1,        3,        5,        5,        3,        3,        3,        3,
         57,       1,        2,        1,        1,        3,        3,        2,        2,
         58,       0,        2,        2,        2,        4,        4,        3,        3,
         59,       0,        3,        3,        3,        2,        2,        4,        4,
         60,       1,        4,        4,        4,        3,        3,        4,        4,
         61,       1,        2,        2,        2,        4,        4,        3,        3,
         62,       1,        2,        2,        2,        4,        4,        2,        3,
         63,       1,        2,        2,        2,        2,        4,        2,        2,
         64,       0,        3,        3,        3,        3,        3,        3,        3,
         65,       1,        4,        3,        3,        4,        3,        4,        3,
         66,       1,        3,        1,        1,        3,        3,        4,        3,
         67,       0,        4,        4,        2,        4,        4,        3,        3,
         68,       0,        3,        2,        2,        3,        2,        3,        4,
         69,       1,        2,        5,        5,        5,        5,        3,        3,
         70,       1,        3,        2,        2,        1,        3,        3,        2,
         71,       1,        3,        3,        2,        3,        3,        3,        3,
         72,       1,        4,        3,        3,        3,        3,        2,        3,
         73,       0,        1,        1,        1,        1,        5,        1,        2,
         74,       0,        3,        3,        3,        3,        3,        3,        3,
         75,       1,        2,        3,        3,        3,        3,        3,        3,
         76,       0,        2,        4,        4,        4,        3,        2,        3,
         77,       1,        1,        2,        5,        2,        2,        5,        3,
         78,       1,        2,        2,        2,        3,        4,        2,        3,
         79,       1,        5,        5,        4,        5,        3,        5,        5,
         80,       1,        2,        1,        2,        2,        2,        3,        3,
         81,       1,        3,        2,        1,        3,        3,        4,        2,
         82,       1,        3,        3,        3,        3,        3,        3,        3,
         83,       0,        2,        3,        3,        3,        3,        2,        4,
         84,       1,        3,        4,        4,        2,        1,        3,        3,
         85,       1,        2,        4,        3,        2,        3,        4,        4,
         86,       1,        4,        4,        4,        2,        2,        4,        3,
         87,       1,        3,        3,        3,        3,        3,        2,        3,
         88,       1,        2,        3,        3,        2,        2,        3,        2,
         89,       0,        4,        1,        2,        5,        3,        1,        4,
         90,       1,        5,        4,        5,        4,        3,        5,        4,
         91,       0,        3,        4,        4,        2,        2,        3,        3,
         92,       1,        4,        2,        2,        3,        3,        4,        2,
         93,       1,        2,        2,        2,        2,        2,        4,        2,
         94,       1,        4,        2,        4,        4,        2,        5,        4,
         95,       1,        4,        3,        3,        4,        3,        5,        3,
         96,       1,        1,        1,        1,        1,        1,        3,        2,
         97,       1,        3,        4,        4,        4,        4,        5,        3,
         98,       1,        4,        4,        4,        3,        3,        4,        3,
         99,       1,        3,        2,        2,        3,        4,        1,        3,
        100,       1,        1,        2,        4,        4,        3,        4,        3,
        101,       1,        4,        4,        4,        3,        3,        5,        4,
        102,       1,        2,        3,        2,        3,        2,        4,        3,
        103,       1,        3,        2,        3,        4,        4,        2,        3,
        104,       1,        2,        3,        2,        5,        5,        3,        2,
        105,       1,        2,        2,        1,        2,        2,        3,        2,
        106,       1,        3,        3,        3,        3,        3,        3,        3,
        107,       1,        4,        2,        3,        4,        4,        5,        5,
        108,       1,        2,        3,        4,        3,        2,        3,        2,
        109,       0,        2,        2,        2,        2,        2,        2,        2,
        110,       1,        2,        3,        4,        3,        4,        2,        4,
        111,       1,        2,        2,        2,        2,        2,        1,        2,
        112,       1,        1,        1,        1,        2,        1,        2,        3,
        113,       1,        4,        3,        2,        3,        2,        4,        3,
        114,       1,        4,        4,        3,        4,        2,        2,        3,
        115,       1,        3,        2,        3,        4,        2,        4,        3,
        116,       0,        5,        4,        4,        5,        4,        4,        4,
        117,       0,        4,        4,        5,        4,        5,        4,        5,
        118,       1,        3,        4,        4,        5,        4,        3,        4,
        119,       1,        3,        1,        1,        1,        1,        3,        3,
        120,       1,        2,        2,        2,        3,        4,        2,        3,
        121,       0,        2,        3,        2,        4,        4,        2,        3,
        122,       1,        4,        4,        4,        4,        4,        4,        4,
        123,       1,        3,        3,        3,        3,        2,        4,        3
  )

#Schlagzeile 10

df10 <- tibble::tribble(
  ~Personen, ~head_10, ~sz10_sd1, ~sz10_sd2, ~sz10_sd3, ~sz10_sd4, ~sz10_sd5, ~sz10_sd6, ~sz10_sd7,
          1,        1,         5,         2,         4,         3,         1,         5,         5,
          2,        0,         4,         3,         4,         3,         4,         4,         4,
          3,        0,         4,         4,         5,         5,         5,         5,         5,
          4,        0,         5,         5,         5,         5,         5,         5,         5,
          5,        0,         4,         3,         4,         5,         5,         2,         5,
          6,        0,         5,         5,         5,         5,         4,         5,         5,
          7,        1,         3,         3,         4,         4,         4,         4,         4,
          8,        0,         4,         4,         5,         4,         4,         5,         4,
          9,        0,         5,         5,         2,         5,         5,         5,         4,
         10,        0,         3,         3,         3,         3,         3,         3,         3,
         11,        0,         2,         2,         2,         4,         1,         3,         3,
         12,        0,         3,         3,         3,         4,         4,         4,         4,
         13,        0,         4,         4,         3,         3,         3,         4,         5,
         14,        0,         3,         2,         3,         2,         4,         4,         3,
         15,        0,         5,         5,         4,         5,         5,         5,         5,
         16,        0,         5,         5,         5,         4,         4,         2,         5,
         17,        0,         4,         5,         5,         5,         5,         5,         4,
         18,        0,         5,         3,         5,         5,         5,         5,         5,
         19,        0,         2,         3,         4,         5,         4,         5,         3,
         20,        1,         4,         5,         5,         4,         5,         5,         4,
         21,        0,         5,         2,         3,         2,         1,         5,         5,
         22,        0,         5,         5,         5,         5,         5,         5,         5,
         23,        0,         4,         4,         4,         3,         3,         4,         4,
         24,        0,         5,         4,         5,         5,         5,         5,         4,
         25,        0,         4,         4,         1,         5,         5,         5,         5,
         26,        0,         4,         4,         4,         5,         5,         4,         4,
         27,        0,         4,         4,         4,         3,         5,         1,         2,
         28,        0,         4,         5,         5,         4,         4,         4,         3,
         29,        0,         3,         4,         4,         5,         5,         3,         5,
         30,        0,         5,         5,         5,         5,         3,         5,         3,
         31,        0,         5,         5,         4,         5,         5,         5,         4,
         32,        0,         5,         4,         4,         4,         4,         5,         5,
         33,        0,         4,         4,         4,         5,         5,         4,         4,
         34,        1,         3,         3,         3,         3,         3,         3,         3,
         35,        0,         2,         2,         2,         2,         2,         5,         5,
         36,        0,         3,         3,         2,         4,         4,         2,         3,
         37,        0,         5,         5,         5,         5,         1,         5,         5,
         38,        0,         4,         3,         5,         3,         5,         5,         3,
         39,        0,         5,         1,         2,         4,         4,         5,         3,
         40,        0,         5,         5,         5,         4,         2,         5,         4,
         41,        0,         4,         5,         4,         3,         1,         5,         3,
         42,        0,         4,         3,         3,         5,         5,         1,         5,
         43,        0,         5,         5,         5,         5,         5,         5,         3,
         44,        1,         4,         4,         5,         5,         4,         5,         5,
         45,        0,         2,         2,         1,         3,         4,         5,         3,
         46,        1,         5,         5,         5,         5,         4,         3,         5,
         47,        0,         2,         2,         3,         4,         5,         4,         4,
         48,        1,         5,         3,         5,         4,         5,         2,         4,
         49,        0,         4,         4,         4,         5,         4,         4,         5,
         50,        0,         4,         5,         5,         5,         4,         4,         4,
         51,        0,         2,         4,         5,         4,         5,         2,         5,
         52,        0,         4,         4,         5,         5,         5,         5,         5,
         53,        0,         1,         1,         1,         1,         1,         1,         1,
         54,        0,         5,         5,         5,         2,         2,         5,         5,
         55,        0,         5,         4,         4,         2,         1,         1,         2,
         56,        0,         5,         5,         5,         5,         4,         5,         5,
         57,        0,         4,         4,         3,         3,         4,         4,         4,
         58,        0,         5,         5,         5,         5,         5,         5,         5,
         59,        0,         5,         5,         5,         2,         2,         5,         5,
         60,        0,         5,         5,         5,         5,         4,         5,         5,
         61,        0,         5,         5,         5,         5,         5,         5,         5,
         62,        0,         3,         3,         3,         4,         4,         5,         4,
         63,        0,         5,         5,         5,         5,         5,         5,         5,
         64,        0,         4,         3,         3,         3,         4,         4,         4,
         65,        1,         4,         5,         5,         5,         4,         5,         4,
         66,        0,         3,         2,         2,         4,         5,         3,         3,
         67,        0,         5,         1,         2,         5,         3,         4,         4,
         68,        1,         4,         5,         5,         5,         4,         5,         5,
         69,        1,         5,         5,         5,         5,         1,         5,         5,
         70,        0,         4,         5,         3,         4,         5,         5,         3,
         71,        0,         2,         2,         2,         3,         3,         2,         2,
         72,        0,         3,         4,         4,         4,         4,         3,         4,
         73,        0,         1,         1,         1,         3,         5,         1,         3,
         74,        0,         1,         1,         1,         4,         5,         3,         3,
         75,        0,         2,         2,         2,         3,         3,         2,         3,
         76,        0,         3,         5,         4,         5,         4,         4,         5,
         77,        0,         2,         3,         3,         4,         5,         1,         3,
         78,        1,         4,         4,         4,         4,         4,         4,         4,
         79,        0,         5,         5,         5,         5,         3,         5,         5,
         80,        0,         5,         3,         4,         3,         4,         5,         5,
         81,        0,         4,         5,         5,         5,         5,         5,         5,
         82,        0,         3,         3,         3,         3,         3,         3,         3,
         83,        1,         3,         4,         4,         4,         4,         2,         3,
         84,        0,         3,         5,         4,         4,         5,         3,         3,
         85,        0,         4,         4,         4,         5,         5,         3,         5,
         86,        1,         4,         5,         5,         3,         4,         3,         3,
         87,        0,         4,         5,         5,         5,         3,         5,         5,
         88,        0,         4,         3,         3,         3,         3,         4,         4,
         89,        0,         5,         1,         5,         3,         2,         4,         2,
         90,        0,         3,         4,         4,         5,         5,         4,         4,
         91,        0,         5,         3,         3,         2,         2,         5,         5,
         92,        1,         4,         4,         4,         4,         4,         3,         4,
         93,        0,         4,         4,         5,         5,         4,         5,         4,
         94,        0,         4,         1,         3,         5,         5,         4,         3,
         95,        0,         5,         5,         5,         5,         3,         5,         4,
         96,        0,         2,         2,         1,         5,         5,         3,         2,
         97,        0,         3,         4,         5,         5,         5,         2,         4,
         98,        0,         4,         4,         4,         5,         5,         5,         5,
         99,        0,         4,         4,         5,         4,         5,         5,         5,
        100,        0,         4,         5,         5,         5,         5,         5,         5,
        101,        1,         4,         4,         4,         5,         5,         5,         4,
        102,        0,         2,         4,         4,         4,         5,         4,         5,
        103,        0,         4,         4,         5,         5,         3,         4,         4,
        104,        0,         4,         3,         4,         5,         4,         5,         3,
        105,        0,         5,         5,         5,         5,         5,         5,         5,
        106,        0,         3,         4,         5,         5,         4,         3,         4,
        107,        0,         4,         4,         3,         5,         5,         5,         5,
        108,        0,         4,         5,         5,         5,         4,         4,         5,
        109,        0,         3,         3,         3,         3,         3,         3,         3,
        110,        0,         5,         5,         5,         5,         4,         2,         4,
        111,        0,         2,         4,         4,         5,         5,         5,         5,
        112,        0,         4,         2,         2,         4,         4,         3,         5,
        113,        0,         4,         5,         5,         5,         4,         5,         5,
        114,        0,         3,         4,         4,         5,         4,         4,         4,
        115,        0,         4,         4,         4,         4,         1,         5,         4,
        116,        1,         5,         4,         4,         5,         5,         5,         5,
        117,        0,         4,         5,         5,         4,         5,         5,         5,
        118,        0,         4,         5,         5,         5,         5,         5,         5,
        119,        0,         3,         2,         3,         5,         4,         5,         4,
        120,        0,         2,         2,         2,         3,         5,         2,         3,
        121,        0,         4,         5,         5,         3,         4,         4,         5,
        122,        0,         4,         4,         5,         4,         4,         5,         4,
        123,        1,         5,         5,         5,         5,         5,         5,         5
  )

#Schlagzeile 11

df11 <- tibble::tribble(
  ~Personen, ~head_11, ~sz11_sd1, ~sz11_sd2, ~sz11_sd3, ~sz11_sd4, ~sz11_sd5, ~sz11_sd6, ~sz11_sd7,
          1,        1,         2,         2,         1,         3,         1,         1,         2,
          2,        0,         2,         3,         4,         4,         4,         2,         3,
          3,        0,         2,         3,         5,         4,         3,         2,         4,
          4,        0,         4,         4,         4,         5,         4,         2,         4,
          5,        1,         3,         4,         4,         4,         4,         3,         2,
          6,        0,         5,         5,         5,         5,         3,         2,         5,
          7,        0,         4,         4,         4,         4,         4,         4,         4,
          8,        1,         3,         4,         3,         4,         4,         2,         3,
          9,        1,         2,         3,         4,         3,         2,         3,         3,
         10,        0,         4,         3,         3,         2,         2,         3,         4,
         11,        0,         2,         2,         2,         4,         2,         3,         3,
         12,        0,         2,         2,         2,         3,         3,         3,         3,
         13,        0,         2,         2,         2,         3,         3,         2,         2,
         14,        0,         3,         3,         3,         3,         2,         3,         3,
         15,        0,         5,         5,         5,         5,         5,         2,         4,
         16,        0,         4,         4,         3,         5,         4,         2,         4,
         17,        0,         2,         3,         3,         4,         4,         1,         3,
         18,        1,         5,         5,         5,         5,         2,         5,         5,
         19,        0,         1,         1,         1,         2,         3,         2,         1,
         20,        1,         4,         5,         3,         5,         3,         2,         4,
         21,        0,         2,         2,         2,         1,         3,         3,         2,
         22,        1,         3,         4,         4,         4,         3,         2,         4,
         23,        0,         2,         2,         3,         2,         4,         2,         2,
         24,        0,         2,         2,         1,         2,         1,         2,         3,
         25,        0,         1,         1,         1,         1,         1,         1,         1,
         26,        0,         2,         3,         3,         5,         5,         2,         3,
         27,        0,         4,         4,         2,         2,         2,         2,         3,
         28,        0,         4,         4,         4,         4,         4,         2,         4,
         29,        0,         3,         4,         4,         3,         3,         2,         2,
         30,        0,         3,         3,         3,         5,         3,         1,         3,
         31,        1,         3,         4,         4,         1,         2,         1,         1,
         32,        1,         2,         2,         2,         2,         2,         1,         2,
         33,        0,         2,         4,         4,         2,         4,         2,         3,
         34,        0,         2,         2,         2,         2,         2,         2,         2,
         35,        0,         5,         5,         5,         1,         1,         1,         3,
         36,        1,         4,         2,         3,         3,         4,         3,         2,
         37,        0,         3,         4,         4,         4,         2,         3,         3,
         38,        1,         4,         5,         1,         1,         3,         5,         3,
         39,        0,         2,         4,         4,         3,         3,         4,         4,
         40,        0,         2,         4,         4,         3,         3,         2,         2,
         41,        0,         2,         3,         4,         4,         1,         2,         3,
         42,        1,         3,         3,         4,         5,         5,         4,         4,
         43,        0,         4,         5,         4,         4,         4,         2,         3,
         44,        0,         4,         5,         4,         2,         1,         2,         4,
         45,        0,         1,         3,         3,         5,         4,         3,         5,
         46,        0,         2,         3,         1,         2,         2,         2,         3,
         47,        0,         4,         4,         3,         3,         2,         2,         3,
         48,        1,         4,         4,         2,         2,         2,         4,         3,
         49,        0,         2,         4,         4,         4,         4,         2,         3,
         50,        0,         3,         4,         4,         2,         4,         2,         3,
         51,        0,         2,         3,         2,         1,         1,         1,         1,
         52,        0,         2,         2,         2,         1,         1,         2,         2,
         53,        0,         1,         1,         1,         1,         1,         1,         1,
         54,        1,         2,         4,         3,         4,         4,         2,         2,
         55,        0,         4,         4,         5,         3,         3,         5,         3,
         56,        0,         3,         4,         4,         3,         2,         2,         3,
         57,        0,         1,         1,         1,         4,         3,         1,         1,
         58,        1,         2,         4,         4,         4,         4,         2,         4,
         59,        0,         3,         3,         3,         3,         2,         2,         3,
         60,        0,         4,         4,         4,         5,         4,         3,         4,
         61,        1,         5,         5,         5,         5,         5,         5,         5,
         62,        0,         3,         3,         3,         2,         3,         3,         3,
         63,        0,         5,         5,         5,         5,         5,         5,         5,
         64,        0,         1,         1,         1,         1,         1,         1,         1,
         65,        0,         4,         5,         5,         5,         4,         2,         4,
         66,        0,         2,         2,         2,         2,         2,         2,         3,
         67,        1,         3,         4,         4,         4,         3,         5,         4,
         68,        0,         3,         5,         4,         4,         3,         1,         2,
         69,        0,         5,         5,         5,         5,         1,         5,         5,
         70,        1,         3,         2,         4,         2,         1,         1,         2,
         71,        0,         1,         1,         1,         3,         3,         2,         2,
         72,        0,         2,         3,         3,         3,         2,         2,         3,
         73,        0,         3,         3,         3,         3,         3,         3,         3,
         74,        0,         1,         3,         3,         3,         3,         3,         3,
         75,        0,         2,         4,         4,         2,         2,         2,         3,
         76,        0,         1,         2,         2,         3,         4,         1,         2,
         77,        0,         4,         4,         4,         3,         1,         2,         5,
         78,        0,         3,         3,         3,         2,         2,         4,         2,
         79,        1,         5,         5,         5,         5,         2,         5,         5,
         80,        0,         1,         2,         2,         2,         2,         2,         2,
         81,        0,         4,         4,         3,         3,         2,         3,         4,
         82,        0,         5,         5,         3,         5,         5,         4,         5,
         83,        0,         3,         5,         4,         3,         3,         2,         5,
         84,        0,         3,         4,         2,         4,         3,         1,         4,
         85,        1,         4,         5,         4,         3,         4,         2,         4,
         86,        1,         2,         4,         5,         5,         5,         1,         3,
         87,        0,         3,         5,         5,         5,         3,         3,         5,
         88,        0,         2,         3,         3,         2,         2,         3,         2,
         89,        0,         4,         2,         3,         4,         2,         3,         5,
         90,        0,         5,         4,         2,         5,         4,         3,         4,
         91,        1,         3,         2,         2,         3,         3,         2,         2,
         92,        1,         2,         4,         4,         2,         3,         2,         3,
         93,        1,         4,         4,         4,         2,         2,         3,         2,
         94,        0,         1,         1,         4,         2,         1,         2,         2,
         95,        0,         4,         4,         5,         5,         3,         5,         4,
         96,        0,         2,         3,         1,         4,         1,         2,         2,
         97,        0,         3,         5,         4,         2,         2,         3,         3,
         98,        0,         3,         3,         3,         3,         3,         3,         3,
         99,        0,         3,         4,         3,         2,         3,         1,         3,
        100,        0,         1,         1,         1,         1,         1,         2,         5,
        101,        1,         4,         4,         5,         5,         5,         4,         5,
        102,        0,         2,         1,         1,         1,         2,         2,         2,
        103,        1,         2,         4,         4,         5,         3,         2,         3,
        104,        0,         2,         2,         2,         3,         2,         2,         2,
        105,        1,         2,         4,         4,         4,         4,         1,         3,
        106,        0,         4,         4,         4,         1,         2,         3,         3,
        107,        1,         5,         4,         4,         5,         4,         5,         5,
        108,        1,         4,         5,         5,         4,         2,         2,         4,
        109,        0,         2,         2,         2,         2,         2,         2,         2,
        110,        1,         1,         4,         4,         5,         2,         2,         2,
        111,        0,         2,         5,         5,         5,         3,         1,         3,
        112,        0,         2,         4,         4,         4,         4,         2,         3,
        113,        0,         3,         4,         2,         1,         2,         3,         3,
        114,        0,         2,         3,         2,         1,         2,         2,         2,
        115,        0,         4,         4,         4,         5,         2,         2,         4,
        116,        1,         2,         5,         5,         5,         3,         3,         4,
        117,        1,         5,         5,         4,         5,         5,         4,         4,
        118,        0,         3,         4,         4,         4,         2,         1,         4,
        119,        1,         4,         5,         4,         3,         3,         2,         4,
        120,        0,         5,         4,         4,         4,         3,         3,         4,
        121,        1,         2,         3,         2,         2,         3,         2,         2,
        122,        0,         4,         5,         4,         3,         3,         4,         3,
        123,        1,         3,         5,         5,         5,         4,         4,         5
  )


# Schlagzeile 12

df12 <- tibble::tribble(
  ~Personen, ~head_12, ~sz12_sd1, ~sz12_sd2, ~sz12_sd3, ~sz12_sd4, ~sz12_sd5, ~sz12_sd6, ~sz12_s7,
          1,        0,         5,         4,         4,         4,         2,         5,        5,
          2,        1,         4,         2,         3,         4,         4,         4,        4,
          3,        0,         4,         5,         4,         5,         5,         5,        5,
          4,        0,         4,         4,         5,         5,         5,         5,        5,
          5,        0,         4,         3,         4,         5,         5,         5,        5,
          6,        0,         5,         5,         4,         5,         5,         5,        5,
          7,        0,         4,         3,         4,         3,         4,         3,        4,
          8,        0,         5,         4,         3,         3,         4,         5,        4,
          9,        1,         5,         4,         4,         5,         5,         5,        5,
         10,        0,         4,         4,         2,         3,         5,         3,        5,
         11,        0,         3,         3,         4,         3,         4,         2,        4,
         12,        1,         3,         3,         3,         3,         2,         2,        3,
         13,        1,         4,         3,         3,         3,         4,         5,        5,
         14,        0,         3,         3,         3,         2,         4,         3,        3,
         15,        0,         5,         5,         5,         5,         5,         5,        5,
         16,        0,         4,         4,         4,         4,         4,         2,        4,
         17,        0,         5,         5,         5,         5,         5,         5,        5,
         18,        0,         2,         1,         1,         1,         1,         5,        5,
         19,        0,         3,         4,         4,         4,         5,         5,        4,
         20,        1,         4,         5,         5,         5,         4,         5,        5,
         21,        0,         5,         5,         1,         4,         5,         5,        5,
         22,        0,         2,         3,         4,         5,         4,         5,        5,
         23,        0,         4,         4,         4,         4,         4,         4,        4,
         24,        0,         5,         3,         4,         5,         4,         4,        5,
         25,        0,         2,         3,         1,         5,         4,         5,        2,
         26,        0,         3,         4,         4,         5,         5,         3,        4,
         27,        0,         4,         2,         2,         3,         5,         1,        2,
         28,        0,         4,         4,         4,         5,         4,         4,        5,
         29,        0,         2,         5,         5,         5,         5,         2,        5,
         30,        1,         5,         5,         5,         5,         5,         5,        5,
         31,        0,         5,         5,         5,         3,         3,         5,        5,
         32,        0,         4,         4,         4,         4,         4,         5,        5,
         33,        0,         4,         4,         4,         5,         4,         4,        4,
         34,        1,         5,         5,         5,         5,         5,         5,        5,
         35,        0,         5,         5,         5,         5,         5,         3,        5,
         36,        0,         4,         3,         3,         4,         2,         4,        3,
         37,        0,         5,         5,         5,         5,         3,         5,        5,
         38,        0,         5,         5,         5,         4,         4,         5,        5,
         39,        1,         2,         3,         4,         4,         2,         3,        4,
         40,        0,         2,         3,         3,         4,         4,         3,        4,
         41,        1,         4,         2,         1,         5,         1,         4,        3,
         42,        0,         4,         4,         4,         5,         5,         5,        5,
         43,        0,         4,         4,         4,         4,         5,         5,        4,
         44,        1,         4,         5,         4,         4,         4,         5,        4,
         45,        0,         1,         1,         1,         5,         5,         5,        5,
         46,        0,         5,         5,         4,         4,         4,         5,        5,
         47,        0,         5,         4,         3,         4,         2,         4,        4,
         48,        1,         5,         2,         2,         2,         2,         3,        4,
         49,        0,         3,         3,         4,         4,         4,         4,        4,
         50,        0,         4,         4,         4,         5,         5,         3,        4,
         51,        0,         2,         4,         5,         5,         5,         2,        4,
         52,        0,         4,         2,         2,         5,         5,         5,        5,
         53,        0,         1,         1,         1,         1,         1,         1,        1,
         54,        0,         5,         4,         5,         1,         1,         5,        5,
         55,        0,         3,         4,         4,         1,         1,         1,        2,
         56,        0,         5,         5,         5,         5,         4,         5,        5,
         57,        0,         2,         2,         3,         3,         4,         2,        4,
         58,        0,         5,         5,         5,         5,         5,         5,        5,
         59,        1,         5,         4,         4,         2,         2,         5,        5,
         60,        1,         4,         4,         5,         5,         4,         5,        5,
         61,        0,         5,         5,         5,         5,         5,         5,        5,
         62,        0,         3,         4,         4,         4,         4,         5,        4,
         63,        0,         5,         3,         3,         3,         3,         4,        3,
         64,        0,         3,         3,         3,         4,         4,         4,        4,
         65,        0,         5,         4,         5,         5,         5,         5,        5,
         66,        0,         4,         4,         4,         5,         5,         4,        3,
         67,        1,         4,         4,         4,         3,         3,         4,        5,
         68,        1,         5,         4,         5,         5,         3,         5,        5,
         69,        0,         5,         5,         5,         1,         1,         5,        1,
         70,        0,         4,         5,         4,         3,         5,         4,        4,
         71,        0,         2,         3,         1,         3,         3,         5,        2,
         72,        0,         3,         3,         3,         4,         4,         3,        3,
         73,        0,         2,         3,         3,         3,         3,         2,        4,
         74,        0,         1,         1,         3,         3,         3,         3,        5,
         75,        0,         3,         2,         2,         4,         4,         2,        4,
         76,        0,         4,         4,         4,         5,         5,         5,        5,
         77,        0,         3,         4,         4,         5,         4,         5,        3,
         78,        0,         4,         4,         4,         4,         4,         4,        4,
         79,        1,         5,         5,         5,         5,         4,         5,        5,
         80,        0,         5,         3,         3,         5,         5,         5,        4,
         81,        0,         3,         2,         2,         4,         4,         4,        4,
         82,        0,         5,         5,         5,         5,         5,         5,        5,
         83,        0,         5,         5,         5,         5,         5,         5,        5,
         84,        0,         4,         4,         5,         5,         3,         3,        3,
         85,        0,         4,         5,         5,         5,         5,         4,        5,
         86,        0,         4,         4,         4,         5,         4,         3,        4,
         87,        0,         5,         5,         5,         5,         3,         5,        5,
         88,        0,         4,         2,         2,         2,         3,         4,        3,
         89,        1,         1,         3,         2,         4,         2,         5,        3,
         90,        0,         3,         5,         5,         5,         5,         3,        4,
         91,        0,         4,         3,         3,         3,         3,         4,        4,
         92,        1,         4,         4,         4,         4,         2,         4,        5,
         93,        0,         4,         4,         4,         4,         4,         4,        4,
         94,        0,         5,         2,         4,         5,         5,         5,        5,
         95,        0,         5,         5,         5,         5,         3,         5,        5,
         96,        0,         5,         5,         5,         5,         4,         4,        5,
         97,        0,         3,         5,         5,         5,         5,         1,        4,
         98,        0,         4,         4,         4,         5,         5,         5,        5,
         99,        1,         4,         5,         4,         5,         5,         4,        5,
        100,        0,         5,         5,         5,         5,         5,         5,        5,
        101,        0,         5,         5,         5,         5,         5,         5,        5,
        102,        0,         4,         4,         3,         5,         5,         5,        5,
        103,        1,         4,         3,         4,         5,         4,         5,        4,
        104,        0,         3,         3,         3,         5,         3,         5,        3,
        105,        0,         4,         4,         4,         5,         5,         5,        5,
        106,        0,         4,         4,         4,         4,         3,         4,        4,
        107,        0,         5,         5,         4,         5,         5,         5,        5,
        108,        0,         4,         5,         5,         5,         5,         4,        5,
        109,        0,         4,         4,         4,         4,         4,         4,        5,
        110,        0,         5,         4,         5,         5,         5,         4,        5,
        111,        0,         4,         4,         4,         5,         5,         5,        5,
        112,        0,         2,         2,         2,         4,         4,         4,        5,
        113,        0,         3,         4,         5,         5,         4,         5,        5,
        114,        0,         3,         4,         4,         4,         4,         4,        4,
        115,        0,         3,         4,         4,         5,         2,         5,        4,
        116,        0,         5,         5,         5,         5,         4,         5,        5,
        117,        0,         5,         4,         4,         4,         5,         5,        5,
        118,        0,         4,         2,         4,         5,         5,         4,        5,
        119,        0,         3,         4,         4,         5,         5,         5,        4,
        120,        0,         4,         4,         4,         5,         5,         4,        3,
        121,        0,         3,         2,         2,         2,         2,         4,        5,
        122,        0,         4,         4,         4,         5,         4,         5,        4,
        123,        0,         3,         3,         3,         5,         5,         5,        4
  )



```



```{r, Test Pivotisieren und semantisches Differenzial}



df <- 


```
```{r, gathering}
raw.short %>% select(starts_with("head_")) %>% 
  pivot_longer(cols = c(head_1, head_2, head_3, head_4, head_5, head_6, head_7, head_8, head_9, head_10, head_11, head_12))
```

## 


```{r pressure, echo=FALSE}

```

